"use strict";
function currentApplication(){return state.applications.find(a=>a.instanceId===instance()?.id);}
function contextTitle(){return currentApplication()?.name||(state.taskAppID?rdText("历史应用 · ")+state.taskAppID:instance()?.id==="default"?rdText("通用助手"):instance()?.name||rdText("历史配置"));}
function sessionInContext(s){return s.instanceId===instance()?.id&&(s.instanceId!=="default"||(state.taskAppID?s.source?.appId===state.taskAppID:s.source?.kind!=="application"));}
function draftKey(){return instance()?.id+":"+ws()?.id+":"+(state.session?.id||"new");}
function stashProductDraft(){if(!state.draftContext||state.view!=="conversation")return;state.drafts.set(state.draftContext,{text:$("#prompt").value,uploads:[...state.uploads],skills:[...state.chosenSkills]});}
function restoreProductDraft(){state.draftContext=draftKey();const d=state.drafts.get(state.draftContext);if(d){$("#prompt").value=d.text;state.uploads=[...d.uploads];state.chosenSkills=[...d.skills];renderAttachments();}}
function updateProductNavigation(){
 const users=state.view==="users";
 const apps=["applications","application"].includes(state.view)||instance()?.id!=="default"||!!state.taskAppID;
 for(const [id,on] of [["nav-users",users],["nav-assistant",!users&&!apps&&state.view!=="tasks"],["nav-applications",!users&&apps&&state.view!=="tasks"],["nav-tasks",state.view==="tasks"]]){const n=$("#"+id);n.classList.toggle("selected",on);if(on)n.setAttribute("aria-current","page");else n.removeAttribute("aria-current");}
 $("#application-count").textContent=state.applications.length||"";$("#page-label").textContent=users?rdText("用户与授权"):state.view==="tasks"?rdText("任务"):state.view==="applications"?rdText("应用"):contextTitle();$("#history-label").textContent=apps?rdText("应用任务"):rdText("通用助手");
 $("#settings-button").textContent=apps?rdText("应用设置"):rdText("助手设置");$("#settings-button").classList.toggle("hidden",["applications","users","tasks"].includes(state.view));$("#new-session").classList.toggle("hidden",apps||state.view!=="conversation");
 $("#back-applications").classList.toggle("hidden",!apps||["applications","users","tasks"].includes(state.view));
 for(const q of ["#trace-button","#debug-button","#workspace-name",".breadcrumb-divider",".sidebar>.workspace",".session-filters","#session-list","#history-label"])$(q).classList.toggle("hidden",state.view!=="conversation");
}
function setProductPage(view){state.view=view;document.body.dataset.view=view;$("#tasks-page").classList.toggle("hidden",view!=="tasks");$(".main-row").classList.toggle("hidden",view!=="conversation");$("#applications-page").classList.toggle("hidden",!["applications","application","users"].includes(view));$("#capability-page").classList.toggle("hidden",view!=="capability");updateProductNavigation();closeConversationSidebar();}
async function refreshApplicationCatalog(){const selection=state.selection;const [a,i,s]=await Promise.all([api("/applications"),api("/instances"),api("/sessions")]);if(selection!==state.selection)return;const id=instance()?.id||"default";state.applications=a;state.instances=i;state.sessions=s;renderInstanceOptions(id);}
async function enterAssistant(){resetConversation();renderInstanceOptions("default");const wid=localStorage.getItem("rundesk-assistant-workspace");if(state.workspaces.some(w=>w.id===wid))$("#workspace").value=wid;setProductPage("conversation");updateWorkspaceLabel();history.replaceState(null,"","#assistant");const sid=localStorage.getItem("rundesk-session"),last=state.sessions.find(s=>s.id===sid&&s.instanceId==="default"&&s.source?.kind!=="application");if(state.drafts.has(draftKey())){restoreProductDraft();renderStatus();}else if(last)await selectSession(last.id);else await selectFirst();renderSessions();}
async function showApplications(){resetConversation();setProductPage("applications");history.replaceState(null,"","#applications");setLoading($("#applications-page"));await refreshApplicationCatalog();if(state.view==="applications")renderApplications();}
function applicationMark(name){return el("div",{class:"application-mark","aria-hidden":"true"},name.trim().slice(0,1).toUpperCase());}
function applicationLink(a){if(!a.entryUrl)return null;try{const u=new URL(a.entryUrl);if(!["http:","https:"].includes(u.protocol)||u.username||u.password)return null;}catch{return null;}return el("a",{class:"app-open",href:a.entryUrl,target:"_blank",rel:"noopener noreferrer"},rdText("打开应用 ↗"));}
function renderApplications(){
 const grid=el("div",{class:"application-grid"});for(const a of state.applications)grid.append(el("article",{class:"application-card","data-app-id":a.appId},el("div",{class:"app-card-top"},applicationMark(a.name),el("span",{class:"app-state"+(a.activeCount?" busy":"")},a.activeCount?rdFormat("${0} 项运行中",a.activeCount):a.sessionCount?rdText("任务已同步"):rdText("已登记"))),el("h2",{},a.name),el("p",{class:"app-description"},a.description||rdText("在专用应用中操作，在这里查看任务与管理能力。")),el("div",{class:"app-metadata"},rdFormat("${0} 条任务记录",a.sessionCount),el("span",{},a.lastActivity?new Date(a.lastActivity).toLocaleDateString():rdText("等待首次任务"))),el("div",{class:"app-card-actions"},button(rdText("查看任务"),()=>showApplication(a.appId),"primary"),button(rdText("设置"),async()=>{await showApplication(a.appId);await openSettings();},"quiet"),applicationLink(a))));
 if(!state.applications.length)grid.append(el("div",{class:"application-empty"},applicationMark("A"),el("h2",{},rdText("把专用应用接进来")),el("p",{},rdText("新闻研究、视频制作等应用接入后，会在这里集中展示。通用助手可直接使用。")),el("p",{class:"help"},rdText("请在新闻研究或视频应用中连接 RunDesk，应用会自动出现在这里。"))));
 $("#applications-page").replaceChildren(el("div",{class:"page-intro"},el("div",{},el("p",{class:"eyebrow"},"YOUR APPLICATIONS"),el("h1",{},rdText("应用")),el("p",{},rdText("每个应用有自己的模型、技能和工具。任务与运行记录，在这里统一查看。"))),el("div",{class:"actions"},button(rdText("刷新"),showApplications,"quiet"))),grid,applicationAdvanced());updateProductNavigation();
}
function taskRow(s){const b=button("",()=>selectSession(s.id),"application-task");b.append(el("div",{},el("strong",{},s.title),el("small",{},(state.workspaces.find(w=>w.id===s.workspaceId)?.name||rdText("项目"))+" · "+new Date(s.updated||s.created).toLocaleString())),el("span",{class:"badge"},(s.archived?rdText("已归档 · "):"")+(statusLabel[s.status]||s.status)));return b;}
function applicationAdvanced(){
 const assigned=new Set(state.applications.map(a=>a.instanceId)),orphan=state.instances.filter(i=>i.id!=="default"&&!assigned.has(i.id)),legacy=state.sessions.filter(s=>s.instanceId==="default"&&s.source?.kind==="application");
 const d=el("details",{id:"application-advanced",class:"advanced-applications"},el("summary",{},rdText("接入说明与历史配置")),el("p",{class:"help"},rdText("旧版应用提交带来源的首条任务后自动归类。没有任务或归属有冲突的配置保留在这里，历史数据不会移动。")),el("details",{class:"integration-notes"},el("summary",{},rdText("开发者接入")),el("p",{},rdText("应用调用 POST /api/v1/applications/{appId}/connect 自动注册并获得绑定。管理员在这里优化配置，无须手动创建实例。")),el("a",{href:"/api/v1/openapi.json",target:"_blank",rel:"noopener"},rdText("查看 API 定义"))));
 for(const i of orphan)d.append(el("div",{class:"legacy-application"},el("div",{},el("strong",{},i.name),el("p",{class:"help"},rdFormat("${0} 条历史对话 · 尚未归类",state.sessions.filter(s=>s.instanceId===i.id).length))),button(rdText("查看"),()=>showLegacyApplication(i.id)),button(rdText("登记为应用"),()=>registerApplicationDialog(i.id))));
 if(legacy.length)d.append(el("h3",{},rdText("默认配置中的历史应用任务")),el("p",{class:"help"},rdText("这些任务仍沿用通用助手配置。新应用应使用专用配置。")),...legacy.map(taskRow));
 if(!orphan.length&&!legacy.length)d.append(el("p",{class:"help"},rdText("没有待归类的历史配置。")));return d;
}
function applicationConnection(a){const info={apiBase:location.origin+"/api/v1",appId:a.appId,instanceId:a.instanceId,workspaceId:a.workspaceId||ws()?.id};return el("details",{class:"application-connection"},el("summary",{},rdText("接入信息")),el("p",{class:"help"},rdText("在应用侧使用这些编号连接已有配置。应用任务仍需明确传入工作区；默认查看项目仅用于此管理界面。")),el("pre",{},json(info)),button(rdText("复制接入信息"),async()=>{await navigator.clipboard.writeText(json(info));toast(rdText("已复制接入信息"));},"quiet"));}
async function showApplication(id){
 const a=state.applications.find(a=>a.appId===id);if(!a)throw Error(rdText("应用不存在，请刷新列表"));resetConversation();renderInstanceOptions(a.instanceId);const ss=state.sessions.filter(s=>s.instanceId===a.instanceId);const wid=a.workspaceId||ss[0]?.workspaceId||state.workspaces[0]?.id;if(wid)$("#workspace").value=wid;setProductPage("application");updateWorkspaceLabel();history.replaceState(null,"","#application/"+encodeURIComponent(id));
 $("#applications-page").replaceChildren(el("div",{class:"page-intro application-heading"},el("div",{},applicationMark(a.name),el("h1",{},a.name),el("p",{},a.description||rdText("专用助手与任务记录"))),el("div",{class:"actions"},applicationLink(a),button(rdText("选用已有能力"),()=>chooseApplicationCapabilities(a),"quiet"),button(rdText("API 凭据"),()=>RunDeskKeys.open(a),"quiet"),button(rdText("编辑应用信息"),()=>registerApplicationDialog(a.instanceId,a),"quiet"))),el("div",{class:"application-settings-grid"},...[ [rdText("运行环境"),rdText("镜像、项目隔离与容器状态"),"environments"],[rdText("模型与认证"),rdText("模型、登录与运行权限"),"instances"],[rdText("技能 Skills"),rdText("完整目录与工作方法"),"skills"],[rdText("工具 MCP"),rdText("业务接口与外部服务"),"mcp"] ].map(([name,help,tab])=>{const b=button("",()=>tab==="environments"?RunDeskEnvironments.open(a):openSettings(tab),"configuration-tile");b.append(el("strong",{},name),el("span",{},help));return b;})),el("section",{class:"application-image-summary",id:"application-image-summary","aria-label":rdText("应用镜像")},rdText("正在读取镜像信息…")),applicationConnection(a),el("div",{class:"task-section-heading"},el("h2",{},rdText("任务记录")),el("span",{class:"muted"},rdFormat("${0} 条",ss.length))),el("div",{class:"application-tasks"},...(ss.length?ss.map(taskRow):[el("div",{class:"application-empty compact"},el("h3",{},rdText("还没有任务")),el("p",{},rdText("从应用发起业务操作后，运行记录会出现在这里。")))])));
 const summary=$("#application-image-summary");if(summary)await RunDeskImages.overview(a,summary);
 const page=$("#applications-page"),grid=page.querySelector('.application-settings-grid'),connection=page.querySelector('.application-connection');
 const config=el('details',{class:'application-config'},el('summary',{},rdText('配置与运行环境')));
 if(grid)config.append(grid);if(summary)config.append(summary);if(connection)config.append(connection);page.append(config);
 page.querySelector('.application-heading').after(el('div',{class:'application-health'},el('span',{},rdText('运行条件尚未检查')),button(rdText('检查运行条件'),()=>RunDeskSetup.open(a),'quiet')));
}
async function showLegacyApplication(iid){resetConversation();renderInstanceOptions(iid);const ss=state.sessions.filter(s=>s.instanceId===iid);if(ss[0])$("#workspace").value=ss[0].workspaceId;setProductPage("application");updateWorkspaceLabel();history.replaceState(null,"","#legacy/"+encodeURIComponent(iid));$("#applications-page").replaceChildren(el("div",{class:"page-intro"},el("div",{},el("p",{class:"eyebrow"},"LEGACY CONFIGURATION"),el("h1",{},instance().name),el("p",{},rdText("原配置与历史对话均已保留，可登记为应用。"))),button(rdText("登记为应用"),()=>registerApplicationDialog(iid),"primary")),el("div",{class:"application-tasks"},...ss.map(taskRow)));}
async function registerApplicationDialog(iid,existing=null){
 const fresh=!iid,i=state.instances.find(x=>x.id===iid)||{name:"",description:""},d=el("dialog",{class:"application-register"});const id=el("input",{id:"register-app-id",value:existing?.appId||"",placeholder:rdText("例如 news2douyin"),required:true,pattern:"[A-Za-z0-9][A-Za-z0-9_.:-]{0,79}",disabled:!!existing});const name=el("input",{id:"register-app-name",value:existing?.name||i.name,required:true,maxlength:160}),description=el("textarea",{rows:2,maxlength:4096},existing?.description||i.description),url=el("input",{type:"url",value:existing?.entryUrl||"",placeholder:"http://127.0.0.1:18080"}),work=el("select",{},...state.workspaces.map(w=>el("option",{value:w.id},w.name)));work.value=existing?.workspaceId||ws()?.id;let createdWorkspaceID="";if(fresh){work.prepend(el("option",{value:"__new__"},rdText("新建独立项目（推荐）")));work.value="__new__";}
 const runtime=el("select",{id:"register-runtime"},el("option",{value:"docker"},rdText("Docker 应用环境")),el("option",{value:"local"},rdText("本机 Codex（兼容已有应用）"))),image=el("input",{id:"register-image",placeholder:rdText("例如 rundesk-news:1.0")}),runtimeFields=el("div",{},el("label",{},rdText("运行方式"),runtime),el("label",{},rdText("应用镜像"),image));image.required=fresh;runtime.onchange=()=>{image.required=fresh&&runtime.value==="docker";image.disabled=runtime.value!=="docker";};
 const error=el("p",{class:"error",role:"status"}),submit=el("button",{type:"submit",class:"primary"},existing?rdText("保存应用信息"):fresh?rdText("添加应用"):rdText("登记应用"));const form=el("form",{},el("div",{class:"dialog-head"},el("h2",{},existing?rdText("应用信息"):fresh?rdText("添加应用"):rdText("登记已有应用")),button(rdText("关闭"),()=>d.close(),"quiet")),el("p",{class:"help"},fresh?rdText("创建应用专用配置。应用软件需单独运行，并通过 API 连接这里的配置。"):rdText("复用现有配置与会话，只增加应用归属信息。")),el("label",{},rdText("应用编号"),id),el("label",{},rdText("显示名称"),name),el("label",{},rdText("用途说明"),description),el("label",{},rdText("默认查看项目"),work),el("label",{},rdText("应用入口（可选）"),url),fresh?runtimeFields:null,error,submit);
 form.onsubmit=async event=>{event.preventDefault();submit.disabled=true;try{if(!iid){const created=await api("/instances",{method:"POST",body:{name:name.value,description:description.value}});iid=created.id;}if(fresh){const current=(await api("/instances")).find(x=>x.id===iid);await api(`/instances/${iid}/execution`,{method:"PUT",body:{revision:current.revision,spec:runtime.value==="docker"?{mode:"docker",image:image.value}:{mode:"local"}}});}if(work.value==="__new__"&&!createdWorkspaceID)createdWorkspaceID=(await api("/workspaces",{method:"POST",body:{name:name.value}})).id;await api("/applications/"+encodeURIComponent(id.value),{method:"PUT",body:{name:name.value,description:description.value,instanceId:iid,workspaceId:work.value==="__new__"?createdWorkspaceID:work.value,entryUrl:url.value,...(existing?{revision:existing.revision}:{})}});state.workspaces=await api("/workspaces");const previousWorkspace=ws()?.id;$("#workspace").replaceChildren(...state.workspaces.map(w=>el("option",{value:w.id},w.name)));if(previousWorkspace)$("#workspace").value=previousWorkspace;await refreshApplicationCatalog();if(d.open){d.close();await showApplication(id.value);}}catch(e){error.textContent=e.message;}finally{submit.disabled=false;}};d.append(form);document.body.append(d);d.addEventListener("close",()=>d.remove(),{once:true});d.showModal();
}
async function renderAssistantSettings(target){
 const resolved=await RunDeskEnvironments.effective(),current=resolved.instance,cp=configPath(ws().id,current.id),model=el("input",{id:"assistant-model",type:"text",value:current.defaultModel,list:"models",placeholder:rdText("留空沿用 Codex 配置")}),permissions=permissionEditor(current),account=el("pre",{id:"assistant-account"},rdText("点击读取登录状态，检查这个助手或应用使用的账户。")),quote=v=>"'"+v.replaceAll("'","'\\''")+"'",ps=v=>"'"+v.replaceAll("'","''")+"'";
 target.replaceChildren(el("section",{class:"card model-settings"},el("h3",{},rdText("默认模型")),el("p",{},rdText("用于新建对话或应用任务。已有会话保留原来选择的模型。")),el("label",{for:"assistant-model"},rdText("模型名称")),model,button(rdText("读取可用模型"),async()=>{const raw=await api(cp("/models"));$("#models").replaceChildren(...(raw.data||[]).map(m=>el("option",{value:m.id||m.model},m.displayName||m.id||m.model)));toast(rdText("模型列表已更新"));},"quiet"),el("details",{class:"advanced-permissions"},el("summary",{},rdText("高级运行权限")),permissions.node),button(rdText("保存配置"),async()=>{await api("/instances/"+current.id,{method:"PATCH",body:{defaultModel:model.value,permissions:permissions.value(),revision:current.revision}});const selected=instance()?.id;state.instances=await api("/instances");renderInstanceOptions(selected);updateWorkspaceLabel();renderStatus();toast(rdText("已保存：默认模型用于新会话，权限在下一轮生效"));await renderSettings();},"primary")),el("section",{class:"card authentication-settings"},el("h3",{},rdText("账户与认证")),el("p",{},resolved.environment?rdText("当前项目环境使用独立认证，下方提供容器登录命令。"):rdText("首次接入需在运行 RunDesk 的电脑上完成 Codex 登录。")),el("div",{class:"actions"},button(rdText("读取登录状态"),async()=>account.textContent=json(await api(cp("/account")))),button(rdText("重新加载"),async()=>{const r=await api("/instances/"+current.id+"/reload",{method:"POST"});toast(rdFormat("已重载 ${0} 个空闲连接，保留 ${1} 个运行中连接",r.closedConnections,r.busyConnections));account.textContent=json(await api(cp("/account")));},"quiet")),account,RunDeskEnvironments.loginDetails(current,resolved.environment)));
}
function contextRoute(){return state.session?"#session/"+encodeURIComponent(state.session.id):state.view==="applications"?"#applications":currentApplication()?"#application/"+encodeURIComponent(currentApplication().appId):instance()?.id!=="default"?"#legacy/"+encodeURIComponent(instance().id):"#assistant";}
async function showCapabilityPage(tab){
 if(state.view!=="capability"){stashProductDraft();state.capabilityReturn={view:state.view,route:contextRoute()};}
 if($("#settings").open)$("#settings").close();state.settingsTab=tab;setProductPage("capability");
 const owner=instance()?.id==="default"&&!state.taskAppID?"assistant":currentApplication()?"application/"+encodeURIComponent(currentApplication().appId):"legacy/"+encodeURIComponent(instance().id);
 history.replaceState(null,"","#"+owner+"/settings/"+tab);
 const page=$("#capability-page");page.replaceChildren(el("div",{class:"page-intro capability-heading"},el("div",{},button(rdText("← 返回"),closeSettings,"quiet back-link"),el("p",{class:"eyebrow"},tab==="skills"?"SKILL LIBRARY":"CONNECTED TOOLS"),el("h1",{},tab==="skills"?rdText("技能 Skills"):rdText("工具 MCP")),el("p",{class:"capability-owner"},rdFormat("配置对象：${0} · 当前项目：${1}",instance()?.id==="default"&&state.taskAppID?rdText("通用助手（历史任务共享；保存会影响通用助手）"):contextTitle(),ws()?.name||""))),el("div",{class:"actions"},button(tab==="skills"?rdText("管理 MCP 工具"):rdText("管理技能"),()=>showCapabilityPage(tab==="skills"?"mcp":"skills"),"quiet"))),el("div",{id:"capability-content"}));await renderSettings();
}
function closeSettings(){if($("#settings").open)$("#settings").close();if(state.view==="capability"){const back=state.capabilityReturn||{view:currentApplication()?"application":"conversation",route:currentApplication()?"#application/"+encodeURIComponent(currentApplication().appId):"#assistant"};setProductPage(back.view);history.replaceState(null,"",back.route);}}
function skillCanBeSelected(){return state.view==="conversation"||state.view==="capability"&&state.capabilityReturn?.view==="conversation";}
function compactConfigurationForms(target,kind){for(const card of [...target.children]){const title=card.querySelector(":scope>h3")?.textContent;if(!title||!(kind==="skills"&&title.includes(rdText("编辑 SKILL.md"))||kind==="mcp"&&title===rdText("添加 / 编辑 MCP")))continue;const d=el("details",{class:"card configuration-editor"},el("summary",{},kind==="skills"?rdText("编辑 SKILL.md / 创建简单技能"):rdText("添加 / 编辑 MCP 服务")));card.before(d);card.classList.remove("card");card.querySelector(":scope>h3").remove();d.append(card);}}
async function restoreProductRoute(){
 const parts=location.hash.slice(1).split("/");let id;try{id=decodeURIComponent(parts[1]||"");}catch{return false;}
 if(parts[0]==="tasks"){await RunDeskTasks.open();return true;}
 if(parts[0]==="trace"){const sid=sessionStorage.getItem("rundesk-trace-session")||localStorage.getItem("rundesk-session");if(state.sessions.some(s=>s.id===sid)){await selectSession(sid);window.RunDeskTraceUI?.open();return true;}}
 if(parts[0]==="assistant"&&parts[1]==="settings"&&["skills","mcp"].includes(parts[2])){await enterAssistant();await showCapabilityPage(parts[2]);return true;}
 if(parts[0]==="users"){await RunDeskUsers.open();return true;}if(parts[0]==="applications"){await showApplications();return true;}
 if(parts[0]==="application"&&state.applications.some(a=>a.appId===id)){await showApplication(id);if(parts[2]==="builds"){await RunDeskBuilds.open(state.applications.find(a=>a.appId===id));return true;}if(parts[2]==="images"){await RunDeskImages.open(state.applications.find(a=>a.appId===id));return true;}if(parts[2]==="environments"){await RunDeskEnvironments.open(state.applications.find(a=>a.appId===id));return true;}if(parts[2]==="settings"&&["skills","mcp"].includes(parts[3]))await showCapabilityPage(parts[3]);return true;}
 if(parts[0]==="legacy"&&state.instances.some(i=>i.id===id)){if(id==="default")await enterAssistant();else await showLegacyApplication(id);if(parts[2]==="settings"&&["skills","mcp"].includes(parts[3]))await showCapabilityPage(parts[3]);return true;}
 if(parts[0]==="session"&&state.sessions.some(s=>s.id===id)){await selectSession(id);return true;}return false;
}
$("#nav-assistant").onclick=()=>safe(enterAssistant);$("#nav-applications").onclick=()=>safe(showApplications);$("#back-applications").onclick=()=>safe(showApplications);
$("#assistant-settings").onclick=()=>safe(async()=>{if(instance()?.id!=="default"||state.taskAppID||!["conversation","capability"].includes(state.view))await enterAssistant();await openSettings();});

async function chooseApplicationCapabilities(a){
 const data=await api('/applications/'+encodeURIComponent(a.appId)+'/available-capabilities');
 const d=el('dialog',{class:'application-register'}),form=el('form'),choices=[];
 form.append(el('h2',{},rdText('选用已有能力')),el('p',{class:'help'},rdText('从通用助手的已安装目录选用，关闭的能力也可选择。只在此应用启用；已有同名配置保留。认证与容器依赖仍需在目标环境可用。')));
 for(const [kind,rows]of [['skills',data.skills.map(s=>s.name)],['mcp',data.mcp]]){form.append(el('h3',{},kind==='skills'?'Skills':'MCP'));for(const name of rows){const input=el('input',{type:'checkbox'});form.append(el('label',{},input,name));choices.push({kind,name,input})}}
 const error=el('p',{role:'status'}),submit=el('button',{type:'submit'},rdText('应用所选能力'));form.append(error,el('div',{class:'actions'},button(rdText('取消'),()=>d.close(),'quiet'),submit));
 form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{await api('/applications/'+encodeURIComponent(a.appId)+'/capabilities',{method:'POST',body:{skills:choices.filter(x=>x.kind==='skills'&&x.input.checked).map(x=>x.name),mcp:choices.filter(x=>x.kind==='mcp'&&x.input.checked).map(x=>x.name)}});d.close();toast(rdText('已为此应用启用所选能力'))}catch(e){error.textContent=e.message}finally{submit.disabled=false}};
 d.append(form);document.body.append(d);d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();
}
