"use strict";
window.RunDeskBuilds=(()=>{
 const labels={draft:"待启动",queued:"排队中",running:"构建中",canceling:"正在取消",canceled:"已取消",interrupted:"状态未确认",failed:"失败",succeeded:"已完成"},active=s=>["queued","running","canceling"].includes(s);
 const endpoint=a=>`/instances/${a.instanceId}/builds`;
 let generation=0,timer;
 async function open(a,selectedID){
  const g=++generation;clearTimeout(timer);if($("#settings").open)$("#settings").close();await refreshApplicationCatalog();if(g!==generation)return;renderInstanceOptions(a.instanceId);setProductPage("application");const hash="#application/"+encodeURIComponent(a.appId)+"/builds";history.replaceState(null,"",hash);
  const page=$("#applications-page"),list=el("div",{class:"build-list"}),detail=el("section",{class:"card build-detail"}),error=el("p",{class:"error",role:"status"});let selected=selectedID,offset=0,logText="",signature="",pollID=0,rendered="";
  page.replaceChildren(el("div",{class:"page-intro"},el("div",{},button("← 镜像版本",()=>RunDeskImages.open(a),"quiet back-link"),el("p",{class:"eyebrow"},"IMAGE BUILDS"),el("h1",{},a.name+" · 构建"),el("p",{},"上传构建目录，查看执行日志，将成功结果登记为镜像版本。")),button("新建构建",()=>upload(a),"primary")),el("p",{class:"card build-policy"},"构建串行执行。成功后不自动更换应用或容器；请到镜像版本页选择并更新。重启后未完成任务标为状态未确认，不自动重跑。"),error,el("div",{class:"build-layout"},list,detail));
  async function poll(){const p=++pollID;if(g!==generation||location.hash!==hash||!page.contains(list))return;
   try{const rows=await api(endpoint(a));if(p!==pollID||g!==generation||location.hash!==hash)return;error.textContent="";
    if(!selected&&rows.length)selected=rows[0].id;
    const nextSignature=JSON.stringify(rows);if(nextSignature!==signature){signature=nextSignature;list.replaceChildren();for(const v of rows){const b=button(v.name,()=>{selected=v.id;offset=0;logText="";signature="";clearTimeout(timer);poll();},"build-title"),card=el("article",{class:"card build-card"+(v.id===selected?" selected":""),"data-build-id":v.id},b,el("span",{class:"badge"},labels[v.status]||v.status),el("p",{class:"help"},new Date(v.created).toLocaleString()),el("p",{class:"help"},`${v.files} 个文件 · ${(v.contextBytes/1048576).toFixed(1)} MiB`));list.append(card);}if(!rows.length)list.append(el("div",{class:"application-empty compact"},el("h2",{},"还没有构建任务"),el("p",{},"将 Dockerfile、工具和技能目录一起打包为 ZIP。上传只保存，不执行。")));}
    const v=rows.find(x=>x.id===selected);if(!v){detail.replaceChildren(el("h2",{},"构建过程"),el("p",{},"选择记录查看状态与日志。"));return;}
    const result=await api(endpoint(a)+`/${v.id}/log?after=${offset}`);if(p!==pollID||g!==generation||location.hash!==hash||selected!==v.id)return;offset=result.next;logText+=result.text;const renderKey=JSON.stringify(v)+":"+offset;if(renderKey===rendered)return;rendered=renderKey;const expanded=detail.querySelector("details")?.open;
    const actions=el("div",{class:"actions"});
    async function action(kind){try{await api(endpoint(a)+`/${v.id}/${kind}`,{method:"POST"});signature="";clearTimeout(timer);await poll();}catch(e){error.textContent=e.message;}}
    if(v.status==="draft")actions.append(button("开始构建",()=>action("start"),"primary"));
    if(v.status==="draft"||active(v.status)){const cancel=button("取消构建",()=>action("cancel"),"quiet");cancel.disabled=v.status==="canceling";actions.append(cancel);}
    if(v.imageVersionId)actions.append(button("查看镜像版本",()=>RunDeskImages.open(a,v.imageVersionId),"primary"));
    if(!active(v.status))actions.append(button("删除记录",async()=>{if(!confirm("删除构建记录、上下文及日志？Docker 镜像和缓存不会删除。"))return;try{await api(endpoint(a)+`/${v.id}`,{method:"DELETE"});selected=null;offset=0;logText="";signature="";clearTimeout(timer);await poll();}catch(e){error.textContent=e.message;}},"quiet"));
    const log=el("pre",{class:"build-log",id:"build-log",tabindex:0},logText||"尚无输出。"),old=detail.querySelector('.build-log'),scroll=old?.scrollTop||0,atBottom=!old||old.scrollHeight-old.scrollTop-old.clientHeight<30;
    detail.replaceChildren(el("div",{class:"build-heading"},el("h2",{},v.name),el("span",{class:"badge",id:"build-status"},labels[v.status])),el("p",{class:"help"},`Dockerfile：${v.dockerfile} · 超时 ${v.timeoutMinutes} 分钟 · ${v.noCache?"不使用缓存":"允许缓存"}`),el("p",{class:"build-reference"},v.reference),el("details",{},el("summary",{},"上下文与镜像身份"),el("p",{class:"build-reference"},"ZIP SHA256："+v.contextSha256),el("p",{class:"build-reference"},"Image ID："+(v.imageId||"尚未生成"))),actions,v.error?el("p",{class:"error"},v.error):document.createTextNode(""),el("div",{class:"build-heading"},el("h3",{},"构建日志"),button("下载已读取日志",()=>{const blob=new Blob([logText],{type:"text/plain;charset=utf-8"}),url=URL.createObjectURL(blob),link=el("a",{href:url,download:v.id+".log"});link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},"quiet")),el("p",{class:"help"},"当前已读取 "+offset+" 字节；最多保留 4 MiB。日志由构建脚本输出，可能包含敏感信息。"),log,v.logTruncated?el("p",{class:"error"},"日志达到 4 MiB，后续输出未保存。"):document.createTextNode(""));
    if(expanded)detail.querySelector("details").open=true;log.scrollTop=atBottom?log.scrollHeight:scroll;
   }catch(e){if(p===pollID&&g===generation)error.textContent=e.message;}finally{if(p===pollID&&g===generation&&location.hash===hash){clearTimeout(timer);timer=setTimeout(poll,1500);}}
  }
  await poll();
 }
 function upload(a){
  const d=el("dialog",{class:"application-register build-dialog"}),error=el("p",{class:"error",role:"status"}),file=el("input",{type:"file",id:"build-zip",accept:".zip",required:true}),name=el("input",{id:"build-name",maxlength:120,placeholder:"例如 新闻工具环境 1.2"}),dockerfile=el("input",{id:"build-dockerfile",value:"Dockerfile",required:true}),minutes=el("input",{id:"build-timeout",type:"number",value:30,min:1,max:120,required:true}),cache=el("input",{type:"checkbox",id:"build-no-cache"}),submit=el("button",{type:"submit",class:"primary"},"上传并保存"),form=el("form",{},el("div",{class:"dialog-head"},el("h2",{},"新建镜像构建"),button("关闭",()=>d.close(),"quiet")),el("label",{},"构建名称",name),el("label",{},"构建目录 ZIP",file),el("label",{},"Dockerfile 路径（相对 ZIP 根目录）",dockerfile),el("label",{},"超时（分钟）",minutes),el("label",{class:"build-checkbox"},cache,"不使用构建缓存"),el("p",{class:"help"},"ZIP 最大 32 MiB，解压后最大 128 MiB、4000 个条目，不接受符号链接。保留 .dockerignore；ZIP 根目录就是构建上下文。"),el("p",{class:"help"},"启动会在本机 Docker 执行 Dockerfile，可联网拉取依赖。不要上传认证文件、API Key 或其他机密。上传后还需点击开始构建。"),error,submit);
  form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{if(file.files[0].size>32*1048576)throw Error("ZIP 最大 32 MiB");const body=new FormData();body.append("file",file.files[0]);body.append("name",name.value);body.append("dockerfile",dockerfile.value);body.append("timeoutMinutes",minutes.value);body.append("noCache",String(cache.checked));const v=await api(endpoint(a),{method:"POST",body});d.close();await open(a,v.id);}catch(e){error.textContent=e.message+"；网络中断时请先查看构建列表，避免重复上传。";}finally{submit.disabled=false;}};
  d.append(form);document.body.append(d);d.addEventListener("close",()=>d.remove(),{once:true});d.showModal();
 }
 return{open};
})();
