"use strict";
(()=>{
 const $=s=>document.querySelector(s),el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;},button=(text,fn,cls)=>{const b=el('button',text,cls);b.type='button';b.onclick=()=>run(fn);return b;};
 let selected='',cfg=null,busy=false,signature='';const labels={running:'进行中',paused:'已暂停调度',waiting:'需要你处理',canceling:'正在取消',canceled:'已取消',completed:'已完成',working:'执行中',queued:'排队中',sending:'正在提交',unconfirmed:'提交待核对',failed:'失败','input-required':'等待远程输入'};
 async function api(path,method='GET',body){const h={'Content-Type':'application/json'};if(method==='POST'&&path==='/collaborations')h['Idempotency-Key']=crypto.randomUUID();const r=await fetch('/api/v1'+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});let v;try{v=await r.json()}catch{throw Error('服务响应不可读')};if(!r.ok)throw Error(v.error||'请求失败');return v}
 async function run(fn){try{$('#error').textContent='';await fn()}catch(e){$('#error').textContent=e.message}}
 function field(host,label,value='',type='input'){host.append(el('label',label));const n=el(type);n.value=value;n.setAttribute('aria-label',label);host.append(n);return n}
 function select(host,label,rows,value){const n=field(host,label,'','select');for(const [id,name]of rows){const o=el('option',name);o.value=id;n.append(o)}n.value=value||rows[0]?.[0]||'';return n}
 function modal(title,build,save){$('#title').textContent=title;$('#fields').replaceChildren();$('#form-error').textContent='';const read=build($('#fields'));$('#form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await save(read());$('#dialog').close();await refresh()}catch(e){$('#form-error').textContent=e.message}finally{b.disabled=false}};$('#dialog').showModal()}
 async function settings(){const [c,instances,spaces]=await Promise.all([api('/collaboration/config'),api('/instances'),api('/workspaces')]);cfg=c;modal('连接与能力',host=>{host.append(el('p','协作管理目前仅向管理员开放。密钥使用服务端环境变量，不写入页面。','small'));const board=el('div');host.append(board);board.append(el('h3','Gitea 黑板（使用已存在的仓库）'));const url=field(board,'Gitea 地址',c.blackboard.url),owner=field(board,'仓库所有者',c.blackboard.owner),repo=field(board,'仓库名',c.blackboard.repo),token=field(board,'Gitea Token 环境变量名',c.blackboard.tokenEnv);host.append(el('h3','Agent 能力目录'));const editors=[],list=el('div');host.append(list);
 function add(a={}){const box=el('div',undefined,'agent-editor'),id=field(box,'Agent ID',a.id),name=field(box,'名称',a.name),description=field(box,'能力说明',a.description,'textarea'),kind=select(box,'执行方式',[['local','已有本地 / Docker 应用'],['remote','远程 A2A 0.3 服务']],a.endpoint?'remote':'local'),local=el('div'),remote=el('div');box.append(local,remote);const instance=select(local,'应用配置',instances.map(x=>[x.id,x.id==='default'?'通用助手':x.name]),a.instanceId),space=select(local,'项目',spaces.map(x=>[x.id,x.name]),a.workspaceId),card=field(remote,'Agent Card URL',a.cardUrl),endpoint=field(remote,'A2A JSON-RPC 地址',a.endpoint),env=field(remote,'Token 环境变量名',a.tokenEnv);remote.append(button('读取能力卡',async()=>{const v=await api('/collaboration/discover','POST',{url:card.value,tokenEnv:env.value});if(v.preferredTransport&&v.preferredTransport!=='JSONRPC')throw Error('请选择 JSONRPC 接口');name.value=v.name||name.value;description.value=[v.description,...(v.skills||[]).map(s=>s.name+': '+s.description)].filter(Boolean).join('\n');endpoint.value=v.url||endpoint.value}));const change=()=>{local.hidden=kind.value!=='local';remote.hidden=kind.value!=='remote'};kind.onchange=change;change();const row={box,read:()=>({id:id.value.trim(),name:name.value.trim(),description:description.value,...(kind.value==='local'?{instanceId:instance.value,workspaceId:space.value}:{endpoint:endpoint.value.trim(),tokenEnv:env.value.trim(),cardUrl:card.value.trim()})})};editors.push(row);box.append(button('移除此登记',()=>box.remove()));list.append(box)}
 for(const a of c.agents)add(a);host.append(button('增加 Agent',()=>add()));return()=>({revision:c.revision,blackboard:{url:url.value.trim(),owner:owner.value.trim(),repo:repo.value.trim(),tokenEnv:token.value.trim()},agents:editors.filter(x=>x.box.isConnected).map(x=>x.read())})},v=>api('/collaboration/config','PUT',v))}
 async function create(){cfg=await api('/collaboration/config');if(!cfg.agents.length){await settings();return}modal('新建协作',host=>{const goal=field(host,'希望完成什么？','','textarea'),leader=select(host,'负责人 Agent',cfg.agents.map(x=>[x.id,x.name])),mode=select(host,'信息交互方式',[['hybrid','黑板 + P2P'],['blackboard','黑板，由负责人委派'],['p2p','P2P，不同步 Gitea']]);host.append(el('label','允许参与的 Agent'));const checks=cfg.agents.map(a=>{const l=el('label'),n=el('input');n.type='checkbox';n.checked=true;l.append(n,document.createTextNode(a.name+' · '+a.description));host.append(l);return{n,a}});const rounds=field(host,'负责人轮次上限','8');rounds.type='number';rounds.min=1;rounds.max=32;return()=>({goal:goal.value,leader:leader.value,mode:mode.value,maxRounds:Number(rounds.value),agents:checks.filter(x=>x.n.checked).map(x=>x.a.id)})},async v=>{const c=await api('/collaborations','POST',v);selected=c.id;signature=''})}
 async function action(kind,text=''){await api('/collaborations/'+selected+'/actions','POST',{action:kind,text});signature='';await refresh()}
 function render(c){const host=$('#detail');host.replaceChildren();host.append(el('span',labels[c.status]||c.status,'badge'),el('h2',c.goal),el('p',`负责人：${c.agents.find(a=>a.id===c.leader)?.name||c.leader} · ${c.mode} · 轮次 ${c.rounds}/${c.maxRounds}`));const bar=el('div',undefined,'toolbar');host.append(bar);if(['running','waiting'].includes(c.status))bar.append(button('暂停调度',()=>action('pause')));if(['paused','waiting'].includes(c.status))bar.append(button('继续',()=>action('resume'),'primary'));if(!['completed','canceled'].includes(c.status))bar.append(button('取消协作',()=>action('cancel')));if(c.boardUrl){try{const u=new URL(c.boardUrl);if(['http:','https:'].includes(u.protocol)){const a=el('a','打开 Gitea 黑板');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';bar.append(a)}}catch{}}
 if(c.error)host.append(el('p',c.error,'warning'));if(c.boardError)host.append(el('p','黑板同步：'+c.boardError,'warning'));if(c.board.url&&!c.issue&&c.boardAttempted)bar.append(button('绑定已创建的 Issue',()=>modal('核对黑板 Issue',h=>{h.append(el('p','请确认 Issue 正文中包含此任务标记：'+c.id));const n=field(h,'Issue 编号');return()=>({issue:Number(n.value)})},v=>api('/collaborations/'+c.id+'/board','POST',v))));if(!['completed','canceled'].includes(c.status)){const f=el('form'),input=el('textarea');input.placeholder='补充要求或回答负责人。等待输入时会自动继续；暂停时请点击“继续”。';input.setAttribute('aria-label','补充要求');const b=el('button','提交补充');b.type='submit';f.append(input,b);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;await run(()=>action('message',input.value));b.disabled=false};host.append(f)}host.append(el('h3','执行进展'));for(const w of c.work){const card=el('div',undefined,'card');card.append(el('strong',(c.agents.find(a=>a.id===w.agent)?.name||w.agent)+' · '+(labels[w.status]||w.status)),el('div',w.id,'meta'));if(w.taskId)card.append(button('查看会话与审批',async()=>{const t=await api('/tasks/'+w.taskId);location.href='/?session='+encodeURIComponent(t.sessionId)}));if(w.status==='unconfirmed')card.append(button('核对远程任务',()=>modal('绑定已接收的远程任务',h=>{h.append(el('p','在远程服务确认该请求的任务 ID，避免重复提交。'));const id=field(h,'远程任务 ID');return()=>({remoteId:id.value.trim()})},v=>api('/collaborations/'+c.id+'/work/'+w.id+'/reconcile','POST',v))));if(w.error)card.append(el('p',w.error,'warning'));if(w.result){const d=el('details');d.append(el('summary','查看结果'),el('pre',w.result));card.append(d)}host.append(card)}host.append(el('h3','共享记录'));for(const e of [...c.entries].reverse()){const box=el('div',undefined,'card');box.append(el('div',`${e.author} · ${e.kind} · ${new Date(e.created).toLocaleString()}`,'meta'),el('pre',e.text));host.append(box)}}
 async function refresh(){if(busy)return;busy=true;try{const rows=await api('/collaborations');$('#runs').replaceChildren();for(const c of rows)$('#runs').append(button(c.goal+' · '+(labels[c.status]||c.status),async()=>{selected=c.id;signature='';await refresh()},selected===c.id?'selected':''));if(!selected&&rows.length)selected=rows[0].id;const c=rows.find(x=>x.id===selected);if(c){const sig=JSON.stringify([c.status,c.work,c.entries,c.error,c.boardError,c.boardUrl,c.rounds]);if(sig!==signature&&(!signature||!$('#detail').contains(document.activeElement))){signature=sig;render(c)}}}finally{busy=false}}
 $('#settings').onclick=()=>run(settings);$('#create').onclick=()=>run(create);$('#close').onclick=()=>$('#dialog').close();setInterval(()=>{if(!$('#dialog').open)run(refresh)},3000);run(refresh);
})();
