"use strict";
window.RunDeskLibrary=(()=>{
 const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const btn=(label,fn,cls)=>{const b=node('button',label,cls);b.type='button';b.onclick=fn;return b;};
 async function request(path,options={}){const r=await fetch('/api/v1'+path,options);if(!r.ok){let v;try{v=await r.json();}catch{}throw Error(v?.error||'请求失败');}return r.json();}
 function dialog(title){const d=node('dialog',undefined,'personal-library-dialog'),head=node('div',undefined,'personal-library-head'),body=node('div');head.append(node('h2',title),btn('关闭',()=>d.close()));d.append(head,body);document.body.append(d);d.onclose=()=>d.remove();d.showModal();return{d,body};}
 function menu(upload,choose){const {d,body}=dialog('添加附件');body.className='personal-library-menu';body.append(btn('上传文件',()=>{d.close();upload();}),btn('从文件库加入',()=>{d.close();open(choose);}));}
 async function preview(f){const {body}=dialog(f.name),url='/api/v1/library/'+f.id+'/content?preview=1',ext=f.name.split('.').pop().toLowerCase();if(['png','jpg','jpeg','gif','webp'].includes(ext)){const img=node('img',undefined,'personal-library-preview');img.src=url;img.alt=f.name;body.append(img);}else if(['mp3','wav','mp4'].includes(ext)){const media=node(ext==='mp4'?'video':'audio',undefined,'personal-library-preview');media.controls=true;media.src=url;body.append(media);}else if(['txt','md','json','log'].includes(ext)&&f.size<1048576){try{const r=await fetch(url);if(!r.ok)throw Error('文件不可用或已删除');body.append(node('pre',await r.text(),'personal-library-text'));}catch(e){body.append(node('p',e.message));}}else{body.append(node('p','此格式请下载后查看。'));}const link=node('a','下载文件');link.href='/api/v1/library/'+f.id+'/content';body.append(link);}
 function open(choose){
  const {d,body}=dialog(choose?'从个人文件库加入':'我的文件'),search=node('input'),toolbar=node('div',undefined,'personal-library-toolbar'),list=node('div',undefined,'personal-library-list'),error=node('p',undefined,'personal-library-error'),upload=node('input');search.type='search';search.placeholder='搜索文件名';search.setAttribute('aria-label','搜索文件名');upload.type='file';upload.multiple=true;upload.hidden=true;
  toolbar.append(search,btn('上传文件',()=>upload.click()));body.append(toolbar,node('p','上传和会话生成的文件会自动保存在这里。','personal-library-help'),upload,error,list);let sequence=0;
  async function refresh(){const seq=++sequence;try{const files=await request('/library?q='+encodeURIComponent(search.value));if(seq!==sequence||!d.open)return;list.replaceChildren();for(const f of files){const row=node('article',undefined,'personal-library-row');row.dataset.fileId=f.id;const info=node('div',undefined,'personal-library-info'),actions=node('div',undefined,'personal-library-actions');info.append(btn(f.name,()=>preview(f),'personal-library-filename'),node('p',`${f.kind==='generated'?'生成':'上传'} · ${(f.size/1024).toFixed(1)} KB · ${new Date(f.created).toLocaleString()}`,'personal-library-help'));const download=node('a','下载');download.href='/api/v1/library/'+f.id+'/content';actions.append(download);if(choose){const add=btn('加入',async()=>{add.disabled=true;try{await choose(f);d.close();}catch(e){error.textContent=e.message;add.disabled=false;}},'primary');actions.prepend(add);}actions.append(btn('删除',async()=>{if(!confirm(`删除“${f.name}”？文件将从个人库移除，历史引用显示已删除。`))return;try{await request('/library/'+f.id,{method:'DELETE'});await refresh();}catch(e){error.textContent=e.message;}}));row.append(info,actions);list.append(row);}if(!files.length)list.append(node('p',search.value?'没有匹配文件':'还没有文件，上传或生成后会自动出现在这里。','personal-library-empty'));}catch(e){error.textContent=e.message;}}
  search.oninput=()=>refresh();upload.onchange=async()=>{error.textContent='';try{for(const f of upload.files){const data=new FormData();data.append('file',f);await request('/library',{method:'POST',body:data});}await refresh();}catch(e){error.textContent=e.message;}finally{upload.value='';}};refresh();
 }
 return{open,menu};
})();
