"use strict";
(()=>{
 const $=q=>document.querySelector(q),node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const S={projects:[],project:null,session:null,generation:0,last:0,messages:new Map(),files:[],busy:false,run:"history",pending:new Map()};
 const statuses={idle:"待开始",starting:"正在启动",running:"执行中",waiting:"等待审批",completed:"已完成",failed:"失败",interrupted:"已中断",queued:"排队中",stopping:"正在停止"},active=s=>["starting","running","waiting","stopping"].includes(s?.status);
 function error(e){const box=$("#member-error");if(box)box.textContent=e.message||String(e);}
 async function request(path,{method="GET",body,raw=false}={}){
  const headers={};let key;
  if(body!==undefined&&!(body instanceof FormData)){headers["Content-Type"]="application/json";body=JSON.stringify(body);}
  if(method==="POST"&&(path.endsWith('/sessions')||path.endsWith('/turns'))){key=path+"\n"+body;if(!S.pending.has(key))S.pending.set(key,crypto.randomUUID());headers['Idempotency-Key']=S.pending.get(key);}
  let r;try{r=await fetch('/api/v1'+path,{method,headers,body});}catch{throw Error('网络中断，提交状态可能尚未确认。请刷新任务列表核对后再重试。');}
  if(r.status===401){document.body.replaceChildren(node('p','登录已失效，正在返回登录页…'));location.replace('/');throw Error('登录已失效');}
  if(!r.ok){let v;try{v=await r.json();}catch{v={message:'请求失败'};}if(key&&r.status<500&&!['request_in_progress','request_unconfirmed'].includes(v.code))S.pending.delete(key);throw Error((v.message||v.error||'请求失败')+(v.requestId?' · 请求 '+v.requestId:''));}
  if(key)S.pending.delete(key);return raw?r.text():r.json();
 }
 const root=()=>'/member/'+S.project.grant.id;
 const button=(text,fn,cls)=>{const n=node('button',text,cls);n.type='button';n.onclick=async()=>{n.disabled=true;try{await fn();}catch(e){error(e);}finally{n.disabled=false;}};return n;};
 function clearSession(){S.generation++;S.session=null;S.last=0;S.messages.clear();S.files=[];S.run='history';for(const id of ['member-messages','member-events','member-approvals','member-files'])$('#'+id).replaceChildren();$('#member-session-title').textContent='新任务';$('#member-status').textContent='';$('#member-stop').hidden=true;$('#member-upload-status').textContent='';}
 async function home(){clearSession();history.replaceState(null,'','#');S.project=null;$('#member-work').hidden=true;$('#member-home').hidden=false;$('#member-error').textContent='';const data=await request('/member/catalog');S.projects=data.projects;$('#member-name').textContent=data.user.name;const list=$('#member-projects');list.replaceChildren();for(const p of S.projects){const card=node('article',undefined,'project'),actions=node('div',undefined,'actions');card.append(node('h2',p.applicationName),node('p',p.projectName));actions.append(node('span',p.canRun?'可执行':'只读','role'),button('进入项目',()=>openProject(p),'primary'));card.append(actions);list.append(card);}if(!S.projects.length)list.append(node('p','暂未分配项目，请联系管理员。'));}
 async function openProject(p){clearSession();S.project=p;history.replaceState(null,'','#project/'+p.grant.id);$('#member-home').hidden=true;$('#member-work').hidden=false;$('#member-project-title').textContent=p.applicationName+' · '+p.projectName;$('#member-role').textContent=p.canRun?'可执行 · 任务与文件在项目内共享':'只读 · 可以查看任务、过程和文件';$('#member-new').disabled=!p.canRun;$('#member-composer').hidden=!p.canRun;await sessions();}
 async function sessions(){const g=S.generation,base=root(),items=await request(base+'/sessions');if(g!==S.generation)return;const list=$('#member-sessions');list.replaceChildren();for(const s of items){const b=button(s.title+' · '+(statuses[s.status]||s.status),()=>select(s));if(s.id===S.session?.id)b.className='selected';list.append(b);}if(!items.length)list.append(node('p','还没有任务'));}
 async function select(s){clearSession();S.session=s;history.replaceState(null,'','#project/'+S.project.grant.id+'/'+s.id);$('#member-session-title').textContent=s.title;await sessions();await poll();}
 function message(key,role){let m=S.messages.get(key);if(!m){const box=node('article',undefined,'message '+(role==='你'?'user':'assistant')),text=node('pre','');box.append(node('strong',role),text,button('复制',()=>navigator.clipboard.writeText(text.textContent)));$('#member-messages').append(box);m={box,text};S.messages.set(key,m);}return m;}
 function events(items){for(const e of items){S.last=e.id;const data=e.data||{},p=data.params||{};if(e.method==='run/input'||e.method==='run/steer'){S.run=data.runId||e.id;message('input-'+e.id,'你').text.textContent=(data.input?.text||'')+(data.input?.files?.length?'\n附件：'+data.input.files.join('、'):'');}
   if(e.direction==='in'&&e.method==='item/agentMessage/delta'){message((p.turnId||S.run)+':'+p.itemId,'Codex').text.textContent+=p.delta||'';}
   if(e.direction==='in'&&e.method==='item/completed'&&p.item?.type==='agentMessage'){message((p.turnId||S.run)+':'+p.item.id,'Codex').text.textContent=p.item.text||'';}
   if(e.method==='item/completed'||e.method==='run/state'||e.method==='error'||e.method.includes('requestApproval')){const d=node('details'),labels={commandExecution:'命令执行',mcpToolCall:'MCP 工具',reasoning:'推理摘要',agentMessage:'模型回复',fileChange:'文件修改',webSearch:'网页搜索'};d.append(node('summary',new Date(e.time).toLocaleTimeString()+' · '+(labels[p.item?.type]||e.method)),node('pre',JSON.stringify(data,null,2)));$('#member-events').append(d);}
  }}
 function renderApprovals(items,base,sid){const box=$('#member-approvals');box.replaceChildren();for(const a of items.filter(a=>a.status==='pending')){const card=node('div',undefined,'approval');card.append(node('strong','等待审批'),node('pre',JSON.stringify(a.request?.params||a.request,null,2)));if(S.project.canRun&&['item/commandExecution/requestApproval','item/fileChange/requestApproval'].includes(a.request?.method)){for(const [label,decision]of [['允许本次','accept'],['拒绝','decline']])card.append(button(label,async()=>{if(decision==='accept'&&!confirm('已检查请求内容，允许本次操作？'))return;await request(base+`/sessions/${sid}/approvals/${a.id}`,{method:'POST',body:{decision,scope:'turn'}});await poll();}));}else card.append(node('p','此类请求请联系管理员处理。'));box.append(card);}}
 async function poll(){if(!S.project||!S.session||S.busy)return;S.busy=true;const g=S.generation,base=root(),sid=S.session.id;try{const [s,ev,approvals,files]=await Promise.all([request(base+'/sessions/'+sid),request(base+`/sessions/${sid}/events?after=${S.last}&limit=500`),request(base+`/sessions/${sid}/approvals`),request(base+`/sessions/${sid}/files`)]);if(g!==S.generation)return;S.session=s;$('#member-session-title').textContent=s.title;$('#member-status').textContent=statuses[s.status]||s.status;$('#member-stop').hidden=!S.project.canRun||!active(s);$('#member-send').disabled=active(s);events(ev);renderApprovals(approvals,base,sid);const list=$('#member-files');list.replaceChildren();for(const f of files){const a=node('a',f.name);a.href='/api/v1'+base+`/workspaces/${S.project.grant.workspaceId}/file?path=`+encodeURIComponent(f.path);a.download=f.name;list.append(a);}if(s.error)$('#member-error').textContent=s.error;}catch(e){if(g===S.generation)error(e);}finally{S.busy=false;}}
 async function create(){const p=S.project,base=root(),g=S.generation,s=await request(base+'/sessions',{method:'POST',body:{workspaceId:p.grant.workspaceId,title:$('#member-prompt').value.trim().slice(0,80)||'新任务'}});if(g!==S.generation)return null;S.session=s;history.replaceState(null,'','#project/'+p.grant.id+'/'+s.id);await sessions();return s;}
 $('#member-composer').onsubmit=async e=>{e.preventDefault();if(!S.project?.canRun)return;const g=S.generation,b=$('#member-send');b.disabled=true;$('#member-error').textContent='';try{const s=S.session||await create();if(!s)return;await request(root()+`/sessions/${s.id}/turns`,{method:'POST',body:{text:$('#member-prompt').value,files:S.files}});if(g!==S.generation)return;$('#member-prompt').value='';S.files=[];$('#member-upload-status').textContent='';await poll();await sessions();}catch(e){error(e);}finally{b.disabled=active(S.session);}};
 $('#member-upload').onchange=async e=>{const f=e.target.files[0],g=S.generation;if(!f)return;try{const data=new FormData();data.append('file',f);const result=await request(root()+`/workspaces/${S.project.grant.workspaceId}/uploads`,{method:'POST',body:data});if(g!==S.generation)return;S.files.push(result.path);$('#member-upload-status').textContent=S.files.length+' 个附件';}catch(e){error(e);}finally{e.target.value='';}};
 $('#member-new').onclick=()=>{clearSession();history.replaceState(null,'','#project/'+S.project.grant.id);$('#member-prompt').value='';$('#member-send').disabled=false;sessions().catch(error);};$('#member-back').onclick=()=>home().catch(error);
 $('#member-stop').onclick=async()=>{try{await request(root()+`/sessions/${S.session.id}/stop`,{method:'POST',body:{expectedRunId:S.session.runId}});await poll();}catch(e){error(e);}};
 $('#member-copy').onclick=async()=>{try{if(S.session)await navigator.clipboard.writeText(await request(root()+`/sessions/${S.session.id}/export?format=markdown`,{raw:true}));}catch(e){error(e);}};
 $('#member-logout').onclick=async()=>{try{await request('/logout',{method:'POST'});location.replace('/');}catch(e){error(e);}};
 async function tick(){await poll();setTimeout(tick,1500);}const initialHash=location.hash.slice(1).split('/');home().then(async()=>{const p=S.projects.find(p=>p.grant.id===initialHash[1]);if(initialHash[0]==='project'&&p){await openProject(p);if(initialHash[2])await select(await request(root()+'/sessions/'+encodeURIComponent(initialHash[2])));}tick();}).catch(error);
})();
