"use strict";
window.RunDeskSchedules=(()=>{
 let signature="",items=[];
 async function refresh(){const rows=await api("/schedules");if(state.view!=="tasks")return;rows.sort((a,b)=>a.created.localeCompare(b.created));items=rows;const sig=json(rows);if(signature===sig)return;signature=sig;
 $("#schedule-list").replaceChildren(el("div",{class:"task-section-heading"},el("h2",{},rdText("定时任务")),button(rdText("新建定时任务"),()=>edit(),"quiet")),el("p",{class:"help"},rdText("按指定时区提交独立任务。暂停队列只暂停执行，定时任务仍会入队。")),...rows.map(s=>el("article",{class:"schedule-card","data-schedule":s.id},el("h3",{},s.spec.name),el("p",{},s.spec.cron+" · "+s.spec.timezone+" · "+(s.spec.enabled?rdText("已启用"):rdText("已停用"))),el("p",{class:"help"},s.nextAt?rdText("下次：")+new Date(s.nextAt).toLocaleString(undefined,{timeZone:s.spec.timezone})+"（"+s.spec.timezone+"）":rdText("没有计划中的执行")),s.lastReason?el("p",{class:"help"},s.lastReason):null,el("div",{class:"actions"},button(rdText("编辑"),()=>edit(s),"quiet"),button(s.spec.enabled?rdText("停用"):rdText("启用"),async()=>{await api("/schedules/"+s.id,{method:"PUT",body:{revision:s.revision,spec:{...s.spec,enabled:!s.spec.enabled}}});await refresh();},"quiet"),s.lastTaskId?button(rdText("最近执行"),async()=>{const t=await api("/tasks/"+s.lastTaskId);await selectSession(t.sessionId);},"quiet"):null,button(rdText("删除"),async()=>{if(!confirm(rdText("删除这个定时规则？已经提交的任务会保留。")))return;await api("/schedules/"+s.id,{method:"DELETE",body:{revision:s.revision}});await refresh();},"quiet")))));
 }
 function edit(s){const spec=s?.spec||{},f=RunDeskTasks.taskFields(spec.task),name=el("input",{id:"schedule-name",required:true,maxlength:120,value:spec.name||""}),cron=el("input",{id:"schedule-cron",required:true,value:spec.cron||"0 9 * * *"}),zone=el("input",{id:"schedule-timezone",required:true,value:spec.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||"Asia/Shanghai"}),enabled=el("input",{id:"schedule-enabled",type:"checkbox",checked:spec.enabled??true}),misfire=el("select",{id:"schedule-misfire"},el("option",{value:"skip"},rdText("跳过错过的时间")),el("option",{value:"once"},rdText("补交一项，不补全部历史"))),overlap=el("select",{id:"schedule-overlap"},el("option",{value:"skip"},rdText("上次未结束则跳过")),el("option",{value:"queue"},rdText("仍然加入队列"))),preview=el("pre",{id:"schedule-preview",role:"status"});misfire.value=spec.misfire||"skip";overlap.value=spec.overlap||"skip";
 RunDeskTasks.dialog(s?rdText("编辑定时任务"):rdText("新建定时任务"),[el("label",{},rdText("规则名称"),name),el("label",{},rdText("Cron（分 时 日 月 周）"),cron),el("label",{},rdText("IANA 时区"),zone),button(rdText("预览未来 5 次"),async()=>{try{const r=await api("/schedules/preview",{method:"POST",body:{cron:cron.value,timezone:zone.value}});preview.textContent=r.times.map(x=>new Date(x).toLocaleString(undefined,{timeZone:r.timezone})+" · "+r.timezone).join("\n");}catch(e){preview.textContent=e.message;}},"quiet"),preview,el("label",{},rdText("错过时间后"),misfire),el("label",{},rdText("与上次任务重叠时"),overlap),el("label",{},enabled,rdText("启用定时任务")),el("h3",{},rdText("执行内容")),...f.fields],async()=>{const value={name:name.value,cron:cron.value,timezone:zone.value,enabled:enabled.checked,misfire:misfire.value,overlap:overlap.value,task:f.value()};await api(s?"/schedules/"+s.id:"/schedules",{method:s?"PUT":"POST",body:s?{spec:value,revision:s.revision}:value});signature="";});
 }
 return {refresh};
})();
