"use strict";
window.RunDeskTasks=(()=>{
 let rows=[],queue=null,cursor="",filter="",signature="",busy=false;
 const labels={...statusLabel,queued:rdText("排队中"),dispatching:rdText("正在接收"),canceled:rdText("已取消"),unconfirmed:rdText("待核对")};
 const pending=t=>["queued","dispatching","starting","running","waiting","stopping"].includes(t.status);
 async function refresh(more=false){if(busy||state.view!=="tasks")return;busy=true;try{const [q,data]=await Promise.all([api("/queue"),api("/tasks?limit="+(more?100:Math.min(500,Math.max(100,rows.length)))+"&status="+encodeURIComponent(filter)+(more&&cursor?"&cursor="+cursor:""))]);if(state.view!=="tasks")return;queue=q;rows=more?[...rows,...data.items]:data.items;cursor=data.nextCursor;render();await window.RunDeskSchedules?.refresh();}catch(e){$("#tasks-error").textContent=e.message;}finally{busy=false;}}
 function render(){const sig=json({rows,queue,cursor,filter});if(sig===signature)return;signature=sig;const opened=new Set([...$("#task-list").querySelectorAll("details[open]")].map(d=>d.dataset.task));
  $("#queue-summary").textContent=rdFormat("全局最多 ${0} 项同时执行 · ${1} · 列表 ${2} 项",queue.maxConcurrent,queue.paused?rdText("调度已暂停"):rdText("调度中"),rows.length);
  $("#queue-toggle").textContent=queue.paused?rdText("恢复调度"):rdText("暂停调度");$("#task-list").replaceChildren(...rows.map(t=>{
   const d=el("details",{class:"queue-task","data-task":t.id,open:opened.has(t.id)},el("summary",{},el("span",{},el("strong",{},t.spec.title),el("small",{},(state.applications.find(a=>a.instanceId===t.spec.instanceId)?.name||rdText("通用助手"))+" · "+new Date(t.created).toLocaleString())),el("span",{class:"badge"},labels[t.status]||t.status)),el("p",{class:"help"},t.reason|| (t.spec.notBefore?rdText("最早执行：")+new Date(t.spec.notBefore).toLocaleString():t.status==="queued"?rdText("按提交顺序等待可用执行额度"):pending(t)?rdText("执行过程可在会话中查看"):rdText("原始执行记录已保留，可进入会话查看结果"))),el("pre",{},t.spec.input.text),el("div",{class:"actions"},button(rdText("查看会话与过程"),()=>selectSession(t.sessionId),"quiet"),pending(t)?button(rdText("取消任务"),async()=>{await api("/tasks/"+t.id+"/cancel",{method:"POST",body:{}});await refresh();},"quiet"):null));return d;
  }));if(!rows.length)$("#task-list").append(el("p",{class:"empty"},rdText("这里还没有任务。新建任务后，可离开此页面，后台会继续调度。")));$("#tasks-more").classList.toggle("hidden",!cursor);$("#tasks-error").textContent="";
 }
 async function open(){resetConversation();setProductPage("tasks");history.replaceState(null,"","#tasks");signature="";await refresh();}
 function dialog(title,fields,save){const d=el("dialog",{class:"task-dialog"}),error=el("p",{class:"error",role:"status"}),submit=el("button",{type:"submit",class:"primary"},rdText("保存"));const form=el("form",{},el("div",{class:"dialog-head"},el("h2",{},title),button(rdText("关闭"),()=>d.close(),"quiet")),...fields,error,submit);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{await save();d.close();signature="";await refresh();}catch(e){error.textContent=e.message;}finally{submit.disabled=false;}};d.append(form);document.body.append(d);d.onclose=()=>d.remove();d.showModal();return d;}
 function taskFields(spec={}){const title=el("input",{id:"task-title",value:spec.title||"",maxlength:120,required:true}),app=el("select",{id:"task-app"},el("option",{value:""},rdText("通用助手")),...state.applications.map(a=>el("option",{value:a.appId},a.name))),work=el("select",{id:"task-workspace"},...state.workspaces.map(w=>el("option",{value:w.id},w.name))),text=el("textarea",{id:"task-text",rows:5,required:true},spec.input?.text||""),model=el("input",{id:"task-model",value:spec.model||"",placeholder:rdText("留空使用默认模型")});app.value=spec.source?.appId||"";work.value=spec.workspaceId||ws()?.id;app.onchange=()=>{const a=state.applications.find(x=>x.appId===app.value);if(a?.workspaceId)work.value=a.workspaceId;};return {fields:[el("label",{},rdText("任务名称"),title),el("label",{},rdText("执行助手或应用"),app),el("label",{},rdText("项目"),work),el("label",{},rdText("任务内容"),text),el("label",{},rdText("模型（可选）"),model)],value:()=>{const a=state.applications.find(x=>x.appId===app.value);return {title:title.value,workspaceId:work.value,instanceId:a?.instanceId||"default",model:model.value,source:a?{kind:"application",appId:a.appId}:{kind:"human"},input:{text:text.value,files:spec.input?.files||[],skills:spec.input?.skills||[]}};}};}
 function create(){const f=taskFields(),at=el("input",{id:"task-not-before",type:"datetime-local"});dialog(rdText("新建任务"),[...f.fields,el("label",{},rdText("最早执行时间（可选，本机时区）"),at)],async()=>api("/tasks",{method:"POST",body:{...f.value(),notBefore:at.value?new Date(at.value).toISOString():""}}));}
 function settings(){const max=el("input",{id:"queue-max",type:"number",min:1,max:16,required:true,value:queue.maxConcurrent}),per=[{id:"default",name:rdText("通用助手")},...state.applications.map(a=>({id:a.instanceId,name:a.name}))].map(i=>({i,input:el("input",{type:"number",min:1,max:16,value:queue.perInstance?.[i.id]||"",placeholder:rdText("继承全局限制")})}));dialog(rdText("并发设置"),[el("p",{class:"help"},rdText("普通对话、队列任务和等待审批的任务共同占用额度。降低上限不会终止正在执行的任务。")),el("label",{},rdText("全局并发"),max),...per.map(x=>el("label",{},x.i.name,x.input))],async()=>{const limits={};for(const x of per)if(x.input.value)limits[x.i.id]=Number(x.input.value);await api("/queue",{method:"PUT",body:{...queue,maxConcurrent:Number(max.value),perInstance:limits}});});}
 async function banner(){const s=state.session,host=$("#queue-banner");if(!s?.taskId||state.view!=="conversation"){host.classList.add("hidden");return};try{const t=await api("/tasks/"+s.taskId);if(state.session?.id!==s.id)return;host.classList.remove("hidden");host.textContent=rdText("队列任务 · ")+(labels[t.status]||t.status)+(t.reason?" · "+t.reason:"");if(["queued","dispatching"].includes(t.status)){for(const id of ["send","archive-session","delete-session"])$("#"+id).disabled=true;} }catch(e){host.classList.remove("hidden");host.textContent=e.message;}}
 $("#processes-open").onclick=()=>RunDeskProcesses.open();$("#usage-open").onclick=()=>RunDeskUsage.open();$("#nav-tasks").onclick=()=>safe(open);$("#new-task").onclick=create;$("#queue-settings").onclick=settings;$("#queue-toggle").onclick=()=>safe(async()=>{await api("/queue",{method:"PUT",body:{...queue,paused:!queue.paused}});await refresh();});$("#tasks-refresh").onclick=()=>refresh();$("#tasks-more").onclick=()=>refresh(true);$("#task-filter").onchange=e=>{filter=e.target.value;refresh();};setInterval(()=>{if(state.view==="tasks")refresh();else banner();},2500);
 return {open,refresh,dialog,taskFields,banner};
})();
