// Fake Docker CLI; browser and real RunDesk HTTP server. No real image build/model.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn,execFileSync}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-builds-')),cli=path.join(temp,'cli'),engine=path.join(temp,'engine');fs.mkdirSync(cli);fs.mkdirSync(engine);fs.copyFileSync('scripts/fixtures/docker-engine.py',path.join(cli,'docker'));fs.chmodSync(path.join(cli,'docker'),0o755);
for(const [name,text]of [['ok','FROM scratch\nLABEL io.rundesk.capabilities.tools="fixture"'],['fail','FROM scratch\n# FIXTURE_FAIL'],['wait','FROM scratch\n# FIXTURE_WAIT']])execFileSync('python3',['-c','import zipfile,sys\nwith zipfile.ZipFile(sys.argv[1],"w") as z:\n z.writestr("Dockerfile",sys.argv[2])\n z.writestr("skills/news/SKILL.md","fixture skill")',path.join(temp,name+'.zip'),text]);
const port=35000+Math.floor(Math.random()*15000),base=`http://127.0.0.1:${port}`,token='builds-admin-token-123456789',checks=[],errors=[];let browser,page,logs='';const server=spawn(path.resolve('bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,PATH:cli+path.delimiter+process.env.PATH,DOCKER_CONFIG:engine,RUNDESK_TOKEN:token},stdio:['ignore','ignore','pipe']});server.stderr.on('data',x=>logs+=x);
const call=async(method,p,body)=>{const r=await fetch(base+'/api/v1'+p,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();assert(r.ok,JSON.stringify(v));return v;};
try{for(let n=0;n<100;n++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
let i=await call('POST','/instances',{name:'新闻专用环境'});i=await call('PUT',`/instances/${i.id}/execution`,{revision:i.revision,spec:{mode:'docker',image:'news:1.0'}});await call('PUT','/applications/news',{name:'新闻研究',instanceId:i.id});
browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(base);await page.locator('#token').fill(token);await page.locator('#login-form button').click();await page.waitForFunction(()=>state.instances.length>1);await page.evaluate(()=>RunDeskImages.open(state.applications.find(a=>a.appId==='news')));await page.getByRole('button',{name:'构建任务',exact:true}).click();await page.getByRole('heading',{name:'还没有构建任务',exact:true}).waitFor();checks.push('image page opens a separate build workbench with empty state');
async function upload(name,fixture){await page.getByRole('button',{name:'新建构建',exact:true}).click();await page.locator('#build-name').fill(name);await page.locator('#build-zip').setInputFiles(path.join(temp,fixture+'.zip'));await page.getByRole('button',{name:'上传并保存',exact:true}).click();await page.locator('#build-status').filter({hasText:'待启动'}).waitFor();}
await upload('新闻工具 1.2','ok');let rows=await call('GET',`/instances/${i.id}/builds`);assert.equal(rows[0].files,2);assert.equal(rows[0].status,'draft');assert(!(fs.existsSync(path.join(engine,'calls.jsonl'))?fs.readFileSync(path.join(engine,'calls.jsonl'),'utf8'):'').split('\n').filter(Boolean).map(JSON.parse).some(x=>x[0]==='build'));checks.push('ZIP stores Dockerfile and skill folder without executing');
await page.getByRole('button',{name:'开始构建',exact:true}).click();await page.locator('#build-status').filter({hasText:'已完成'}).waitFor();await page.locator('#build-log').filter({hasText:'fixture build complete'}).waitFor();rows=await call('GET',`/instances/${i.id}/builds`);const success=rows[0];assert(success.imageVersionId);assert.equal((await call('GET','/instances')).find(x=>x.id===i.id).execution.image,'news:1.0');assert(!fs.existsSync(path.join(temp,'demo','image-builds',success.id,'context')));checks.push('successful build streams logs, registers immutable image and preserves app target; context removed');
assert(!(await page.locator('.build-detail').innerText()).split('\n').includes('null'));const out='docs/screenshots/0.12.0';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/builds-desktop.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/builds-mobile.png'});assert(await page.evaluate(()=>document.querySelector('#applications-page').scrollWidth<=document.querySelector('#applications-page').clientWidth));checks.push('build page fits desktop and mobile');await page.setViewportSize({width:1440,height:1000});
await page.reload();await page.locator('#build-log').filter({hasText:'fixture build complete'}).waitFor();checks.push('build route and logs persist after refresh');await page.getByRole('button',{name:'查看镜像版本',exact:true}).click();await page.locator(`[data-image-version-id="${success.imageVersionId}"]`).waitFor();checks.push('successful result opens the registered image version');await page.getByRole('button',{name:'构建任务',exact:true}).click();
await upload('失败日志','fail');await page.getByRole('button',{name:'开始构建',exact:true}).click();await page.locator('#build-status').filter({hasText:'失败'}).waitFor();await page.locator('#build-log').filter({hasText:'fixture dependency failed'}).waitFor();checks.push('build failure shows stderr and terminal status');
await upload('取消验证','wait');await page.getByRole('button',{name:'开始构建',exact:true}).click();await page.locator('#build-log').filter({hasText:'fixture build started'}).waitFor();await page.getByRole('button',{name:'取消构建',exact:true}).click();await page.locator('#build-status').filter({hasText:'已取消'}).waitFor();checks.push('running build can be canceled without retry');await page.getByRole('button',{name:'删除记录',exact:true}).click();await page.locator('.build-card').filter({hasText:'取消验证'}).waitFor({state:'detached'});checks.push('terminal record and retained files can be deleted');
assert.deepEqual(errors,[]);checks.push('no uncaught browser exceptions');const report={mode:'fake Docker CLI; no actual image build or model',passed:checks.length,checks};fs.writeFileSync('docs/builds-validation-0.12.0.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}catch(e){console.error(e.stack,logs);await page?.screenshot({path:path.join(temp,'failure.png')}).catch(()=>{});console.error(temp);process.exitCode=1;}finally{await browser?.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}if(!process.exitCode)fs.rmSync(temp,{recursive:true,force:true});}})();
