// Real RunDesk + Chromium, with explicit fault responses injected at the browser boundary.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-errors-')),port=34000+Math.floor(Math.random()*17000),base=`http://127.0.0.1:${port}`,token='diagnostics-test-token-1234567890';
 const server=spawn(path.resolve('bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,RUNDESK_TOKEN:token},stdio:['ignore','ignore','pipe']});let logs='',browser,page;server.stderr.on('data',x=>logs+=x);const checks=[],errors=[],out=path.resolve('docs/screenshots/0.9.2');fs.mkdirSync(out,{recursive:true});
 const call=async(method,p,body)=>{const r=await fetch(base+'/api/v1'+p,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)});assert(r.ok,await r.text().then(t=>`${r.status} ${t}`));};
 const trigger=(p,options)=>page.evaluate(async({p,options})=>{try{await api(p,options);}catch(e){return {message:e.message,id:e.diagnosticId,status:e.status};}},{p,options});
 const entries=()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem('rundesk-diagnostics-v1')||'[]'));
 try{
  for(let i=0;i<100;i++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:960}});page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedDiagnostic=text;}}});});
  await page.goto(base);await page.locator('#token').fill(token);await page.locator('#login-form button').click();await page.waitForFunction(()=>state.workspaces.length>0);assert.equal((await entries()).length,0);
  const sid=await page.evaluate(async()=>{const s=await newSession();return s.id;});
  let num=0;
  await page.route('**/api/v1/fixtures/**',async route=>{
   const name=new URL(route.request().url()).pathname.split('/').at(-1);
   if(name==='network'){await route.abort('failed');return;}
   if(name==='html'){await route.fulfill({status:500,contentType:'text/html',body:'<html><h1>proxy upstream failed</h1><script>window.injectedError=true</script><img src=x onerror=alert(1)></html>'});return;}
   if(name==='empty'){await route.fulfill({status:502,body:''});return;}
   if(name==='invalid'){await route.fulfill({status:200,contentType:'text/html',body:'Gateway login page'});return;}
   if(name==='large'){await route.fulfill({status:500,contentType:'text/plain',body:'api_key=large-secret\n'+'x'.repeat(200000)});return;}
   await route.fulfill({status:500,contentType:'application/json',headers:{'X-Request-ID':'request-'+(++num),'Idempotency-Replayed':'true'},body:JSON.stringify({error:'配置读取失败：上游服务返回 HTTP 500',code:'internal_error',requestId:'original-request',retryable:false,details:{origin:'codex_rpc',rpcCode:-32001,causes:['model/list: upstream temporarily unavailable'],api_key:'secret-123',nested:{Authorization:'Bearer hidden-token'},url:'https://user:password@example.org?token=abc'}})});
  });
  const failure=await trigger('/fixtures/json');assert.equal(failure.status,500);await page.locator('#diagnostics-button').click();await page.locator('#diagnostics-response').waitFor();let detail=await page.locator('#diagnostics-detail').innerText();assert.match(detail,/HTTP 500/);assert.match(detail,/GET \/api\/v1\/fixtures\/json/);assert.match(detail,/request-1/);assert.match(detail,/original-request/);assert.match(detail,/model\/list/);assert(!detail.includes('secret-123'));assert(!detail.includes('hidden-token'));assert.equal(JSON.parse((await entries())[0].response).details.api_key,'[redacted]');
  await page.locator('#diagnostics-copy').click();assert.match(await page.evaluate(()=>window.copiedDiagnostic),/request-1/);assert(!(await page.evaluate(()=>window.copiedDiagnostic)).includes('secret-123'));await page.screenshot({path:out+'/http500-desktop.png'});checks.push('JSON HTTP 500 displays URL, method, status, request IDs, session, code and upstream cause; copy uses redacted content');
  await trigger('/fixtures/json');assert.equal((await entries()).length,1);assert.equal((await entries())[0].count,2);assert.deepEqual((await entries())[0].requestIds,['request-1','request-2']);checks.push('repeated identical requests group with count, timestamps and recent correlation IDs');
  await trigger('/fixtures/html');await page.locator('.diagnostics-item').first().click();assert.match(await page.locator('#diagnostics-response').innerText(),/proxy upstream failed/);assert.equal(await page.locator('#diagnostics-response script').count(),0);assert.equal(await page.evaluate(()=>window.injectedError),undefined);checks.push('HTML 500 response remains inert text and is not discarded by JSON parsing');
  await trigger('/fixtures/empty');let last=(await entries())[0];assert.equal(last.status,502);assert.match(last.message,/未提供错误内容/);
  await trigger('/fixtures/invalid');last=(await entries())[0];assert.equal(last.status,200);assert.equal(last.kind,'protocol');assert.match(last.response,/Gateway login page/);
  await trigger('/fixtures/network');last=(await entries())[0];assert.equal(last.kind,'network');assert.equal(last.status,undefined);checks.push('empty 502, HTTP 200 invalid JSON, and no-response network failure are distinguished without inventing a 500');
  await trigger('/fixtures/large');last=(await entries())[0];assert.equal(last.truncated,true);assert(last.response.length<33000);assert(!last.response.includes('large-secret'));checks.push('oversized errors are bounded at 32 KiB with an explicit truncation indication');
  await page.getByRole('button',{name:'关闭错误记录',exact:true}).click();await page.reload();await page.waitForFunction(()=>state.workspaces.length>0);await page.locator('#diagnostics-button').click();assert((await entries()).length>=6);await page.getByRole('button',{name:'关闭错误记录',exact:true}).click();checks.push('error history remains available after refresh in the same tab');
  await page.evaluate(()=>document.querySelector('#settings').showModal());await trigger('/fixtures/json');await page.locator('#settings .diagnostics-inline button').click();assert(await page.locator('#diagnostics-dialog').isVisible());await page.getByRole('button',{name:'关闭错误记录',exact:true}).click();await page.locator('#close-settings').click();checks.push('errors inside settings dialogs have a reachable detail action without closing the original form');
  await page.evaluate(id=>selectSession(id),sid);const keys=[];
  await page.route(`**/api/v1/sessions/${sid}/turns`,async route=>{keys.push(route.request().headers()['idempotency-key']);await route.fulfill({status:500,contentType:'text/html',body:'upstream temporarily unavailable'});});
  await page.locator('#prompt').fill('private-request-body-marker');await page.locator('#send').click();await page.locator('#send-feedback').filter({hasText:'输入已保留'}).waitFor();await page.waitForFunction(()=>!state.sending);assert.equal(await page.locator('#prompt').inputValue(),'private-request-body-marker');assert.equal(keys.length,1);assert(!JSON.stringify(await entries()).includes('private-request-body-marker'));
  await page.locator('#toast .diagnostics-link').click();assert.match(await page.locator('#diagnostics-detail').innerText(),/POST[\s\S]*turns/);await page.getByRole('button',{name:'关闭错误记录',exact:true}).click();await page.locator('#send').click();await page.waitForFunction(()=>!state.sending);assert.equal(keys.length,2);assert.equal(keys[0],keys[1]);checks.push('failed send retains the draft and exposes details; only manual retry occurs and keeps the same idempotency key; request body is excluded');
  await page.evaluate(()=>{const e={id:999001,time:new Date().toISOString(),method:'run/state',data:{runId:'fixture-run',status:'failed',error:'HTTP 500 from provider; upstream request failed'}};state.stream.onmessage({data:JSON.stringify(e)});});
  await page.locator('.run-error .diagnostics-link').click();assert.match(await page.locator('#diagnostics-detail').innerText(),/Codex 运行/);assert.match(await page.locator('#diagnostics-detail').innerText(),/未获取到 HTTP 状态/);assert.match(await page.locator('#diagnostics-detail').innerText(),/999001/);await page.getByRole('button',{name:'关闭错误记录',exact:true}).click();checks.push('runtime error card opens event details and does not mislabel an upstream 500 as a browser HTTP status');
  await page.evaluate(()=>{const e={id:999002,time:new Date().toISOString(),method:'run/state',data:{runId:'fixture-run',status:'failed',error:'HTTP 500 from provider; upstream request failed'}};RunDeskDiagnostics.captureEvent(e,state.session);RunDeskDiagnostics.captureEvent({...e,id:999001},state.session);});assert.equal((await entries()).find(r=>r.kind==='runtime').count,2);
  checks.push('replayed event IDs do not inflate counts after runtime errors were grouped');
  await page.evaluate(()=>{state.stream.onerror();state.stream.onerror();});assert.equal((await entries()).filter(r=>r.kind==='stream').length,1);checks.push('SSE disconnect is recorded once per outage with unknown HTTP status');
  await page.locator('#trace-button').click();await page.locator('#trace-diagnostics-button').click();assert(await page.locator('#diagnostics-dialog').isVisible());await page.getByRole('button',{name:'关闭错误记录',exact:true}).click();await page.locator('#trace-close').click();
  await page.setViewportSize({width:390,height:844});await page.locator('#diagnostics-button').click();await page.locator('.diagnostics-item').filter({hasText:'配置读取失败'}).click();await page.screenshot({path:out+'/http500-mobile.png'});assert(await page.locator('#diagnostics-dialog').evaluate(n=>n.scrollWidth<=n.clientWidth+1));await page.keyboard.press('Escape');assert(!await page.locator('#diagnostics-dialog').isVisible());assert(await page.locator('#shell').evaluate(n=>n.scrollWidth<=n.clientWidth+1));checks.push('trace entry, 390px mobile details and Escape work without horizontal overflow');
  await page.locator('#diagnostics-button').click();await page.locator('#diagnostics-clear').click();assert.equal((await entries()).length,0);assert.match(await page.locator('#diagnostics-detail').innerText(),/尚无错误/);checks.push('clear removes the current tab history');assert.deepEqual(errors,[]);checks.push('no uncaught browser JavaScript errors');
  const report={mode:'real RunDesk demo service and Chromium; explicit browser HTTP faults and synthetic runtime event; no real provider fault reproduced',passed:checks.length,checks};fs.writeFileSync('docs/diagnostics-validation-0.9.2.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }catch(e){if(page)await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});console.error(e);console.error(logs.slice(-1200));process.exitCode=1;}
 finally{if(browser)await browser.close();server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));fs.rmSync(temp,{recursive:true,force:true});}
})();
