// Fake Docker CLI + real lease supervisor + demo JSONL; never a paid model call.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-docker-')),cli=path.join(temp,'cli'),engine=path.join(temp,'engine');fs.mkdirSync(cli);fs.mkdirSync(engine);const fixture=path.join(cli,'docker');fs.copyFileSync('scripts/fixtures/docker-engine.py',fixture);fs.chmodSync(fixture,0o755);
 const port=35000+Math.floor(Math.random()*15000),base=`http://127.0.0.1:${port}`,token='docker-demo-admin-token-1234567890',checks=[],errors=[];let browser,page,logs='';
 const server=spawn(path.resolve('bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,PATH:cli+path.delimiter+process.env.PATH,DOCKER_CONFIG:engine,RUNDESK_TOKEN:token},stdio:['ignore','ignore','pipe']});server.stderr.on('data',x=>logs+=x);
 const call=async(method,p,body)=>{const r=await fetch(base+'/api/v1'+p,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body?JSON.stringify(body):undefined});const data=await r.json();assert(r.ok,`${method} ${p}: ${r.status} ${JSON.stringify(data)}`);return data;};
 const waitSession=async id=>{for(let n=0;n<120;n++){const s=await call('GET','/sessions/'+id);if(s.status==='completed')return s;if(s.status==='failed')throw Error(s.error);await new Promise(r=>setTimeout(r,100));}throw Error('session timeout');};
 try{
  for(let n=0;n<100;n++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await page.locator('#token').fill(token);await page.locator('#login-form button').click();await page.waitForFunction(()=>state.workspaces.length>0);
  assert.equal(await page.locator('#page-label').innerText(),'通用助手');assert.equal((await call('GET','/instances')).find(i=>i.id==='default').execution.mode,'local');checks.push('general assistant stays native');
  await page.locator('#nav-applications').click();await page.getByRole('button',{name:'添加应用',exact:true}).first().click();assert.equal(await page.locator('#register-runtime').inputValue(),'docker');await page.locator('#register-app-id').fill('docker-news');await page.locator('#register-app-name').fill('新闻研究');await page.locator('#register-image').fill('rundesk-news:1.0');await page.locator('.application-register button[type=submit]').click();await page.getByRole('button',{name:'运行环境',exact:false}).click();await page.locator('#execution-image').waitFor();assert.equal(await page.locator('#execution-image').inputValue(),'rundesk-news:1.0');checks.push('new app configures Docker and opens dedicated runtime page');
  await page.getByRole('button',{name:'新建独立项目',exact:true}).click();await page.locator('#environment-project-name').fill('政策背景研究');await page.locator('.application-register button[type=submit]').click();await page.locator('.environment-card').waitFor();assert(!fs.existsSync(path.join(engine,'calls.jsonl')));checks.push('creating environment metadata does not launch Docker');
  await page.getByRole('button',{name:'新建独立项目',exact:true}).click();await page.locator('#environment-project-name').fill('市场事件研究');await page.locator('.application-register button[type=submit]').click();await page.waitForFunction(()=>document.querySelectorAll('.environment-card').length===2);
  const a=await call('GET','/applications/docker-news');assert.notEqual(a.workspaceId,(await call('GET','/workspaces')).find(w=>w.name==='默认工作区').id);const envs=await call('GET','/environments?instanceId='+a.instanceId),first=envs[0];assert.notEqual(envs[0].codexHome,envs[1].codexHome);checks.push('one app has two independent project environments');
  await page.locator(`[data-environment-id="${first.id}"]`).getByRole('button',{name:'启动',exact:true}).click();await page.locator(`[data-environment-id="${first.id}"] .badge`).filter({hasText:'运行中'}).waitFor();checks.push('UI starts managed environment');
  const session=await call('POST','/sessions',{instanceId:a.instanceId,workspaceId:first.workspaceId,title:'容器研究演示'});await call('POST',`/sessions/${session.id}/turns`,{text:'研究新闻背景'});const finished=await waitSession(session.id);assert.equal(finished.environmentId,first.id);const runtime=await call('GET',`/sessions/${session.id}/runtime`);assert.equal(runtime.codexHome,first.codexHome);checks.push('real supervisor carries demo App Server JSONL with correct environment home');
  const sentinel=path.join(first.codexHome,'keep.txt');fs.writeFileSync(sentinel,'persistent');await page.getByRole('button',{name:'刷新列表',exact:true}).click();page.on('dialog',d=>d.accept());await page.locator(`[data-environment-id="${first.id}"]`).getByRole('button',{name:'重建容器',exact:true}).click();await page.locator(`[data-environment-id="${first.id}"] .badge`).filter({hasText:'运行中'}).waitFor();assert.equal(fs.readFileSync(sentinel,'utf8'),'persistent');await call('POST',`/sessions/${session.id}/turns`,{text:'继续分析'});const resumed=await waitSession(session.id);assert.equal(resumed.threadId,finished.threadId);checks.push('recreate preserves host data and resumes native thread');
  await page.locator(`[data-environment-id="${first.id}"]`).getByRole('button',{name:'配置此项目的能力',exact:true}).click();await page.locator('[data-settings-tab=instances]').click();await page.locator('.authentication-settings summary').click();assert.match(await page.locator('.authentication-settings').innerText(),/docker exec -it/);assert((await page.locator('.authentication-settings').innerText()).includes(first.codexHome));await page.locator('#close-settings').click();checks.push('authentication points to selected project container');
  await page.getByRole('button',{name:'刷新列表',exact:true}).click();const out='docs/screenshots/0.11.0';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/docker-environments-desktop.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/docker-environments-mobile.png'});assert(await page.evaluate(()=>document.querySelector('#applications-page').scrollWidth<=document.querySelector('#applications-page').clientWidth));checks.push('runtime page fits desktop and mobile');
  fs.writeFileSync(path.join(engine,'offline'),'1');await page.locator(`[data-environment-id="${first.id}"]`).getByRole('button',{name:'核对状态',exact:true}).click();await page.locator(`[data-environment-id="${first.id}"] .error`).filter({hasText:'Docker'}).waitFor();checks.push('Docker failure is visible in the environment card');fs.unlinkSync(path.join(engine,'offline'));
  await page.reload();await page.locator('#execution-image').waitFor();assert.equal(await page.locator('.environment-card').count(),2);checks.push('runtime route survives refresh');assert.deepEqual(errors,[]);checks.push('no uncaught browser errors');
  const report={mode:'fake Docker CLI; real lease supervisor; native demo JSONL; no real Docker or model',passed:checks.length,checks};fs.writeFileSync('docs/docker-validation-0.11.0.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }catch(e){console.error(e.stack,logs);if(page)await page.screenshot({path:path.join(temp,'failure.png')}).catch(()=>{});console.error('fixture debug directory',temp);process.exitCode=1;}
 finally{await browser?.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}if(!process.exitCode)fs.rmSync(temp,{recursive:true,force:true});}
})();
