// Image registry/UI contract against a fake local Docker Engine. No model or real container.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-images-')),cli=path.join(temp,'cli'),engine=path.join(temp,'engine');fs.mkdirSync(cli);fs.mkdirSync(engine);const fixture=path.join(cli,'docker');fs.copyFileSync('scripts/fixtures/docker-engine.py',fixture);fs.chmodSync(fixture,0o755);
 const port=35000+Math.floor(Math.random()*15000),base=`http://127.0.0.1:${port}`,token='images-demo-admin-token-1234567890',checks=[],errors=[];let browser,page,logs='';
 const server=spawn(path.resolve('bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,PATH:cli+path.delimiter+process.env.PATH,DOCKER_CONFIG:engine,RUNDESK_TOKEN:token},stdio:['ignore','ignore','pipe']});server.stderr.on('data',x=>logs+=x);
 const call=async(method,p,body)=>{const r=await fetch(base+'/api/v1'+p,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();assert(r.ok,`${method} ${p}: ${r.status} ${JSON.stringify(data)}`);return data;};
 try{
  for(let n=0;n<100;n++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
  let i=await call('POST','/instances',{name:'新闻研究'});i=await call('PUT',`/instances/${i.id}/execution`,{revision:i.revision,spec:{mode:'docker',image:'news:1.0'}});const w=await call('POST','/workspaces',{name:'每日新闻'});await call('PUT','/applications/news',{name:'News2Douyin',description:'新闻背景研究与证据整理',instanceId:i.id,workspaceId:w.id});
  let v=await call('POST','/environments',{instanceId:i.id,workspaceId:w.id});v=await call('POST',`/environments/${v.id}/actions`,{action:'start',revision:v.revision});const initial=v.imageId;fs.writeFileSync(path.join(v.codexHome,'keep.txt'),'persistent');
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1050}});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  await page.goto(base);await page.locator('#token').fill(token);await page.locator('#login-form button').click();await page.waitForFunction(()=>state.workspaces.length>0);
  await page.locator('#nav-applications').click();await page.getByRole('button',{name:'查看任务',exact:true}).click();await page.getByRole('button',{name:'镜像与构建',exact:true}).click();await page.getByText('还没有登记镜像',{exact:true}).waitFor();checks.push('separate image page has an explicit empty state');
  await page.getByRole('button',{name:'登记当前镜像',exact:true}).click();assert.equal(await page.locator('#image-register-reference').inputValue(),'news:1.0');await page.getByRole('button',{name:'检查并登记',exact:true}).click();await page.locator('.image-version').waitFor();let c=await call('GET',`/instances/${i.id}/images`);assert.equal(c.versions.length,1);assert.equal(c.execution.imageVersionId,undefined);checks.push('registration inspects without changing the application target');
  assert((await page.locator('.image-detail').innerText()).includes('fixture-only'));assert((await page.locator('.image-detail').innerText()).includes('未提供'));assert(!(await page.locator('.image-detail').innerText()).includes('hidden-fixture'));checks.push('producer metadata and missing fields are clear; unrelated image config is hidden');
  await page.getByRole('button',{name:'设为应用版本',exact:true}).click();await page.getByRole('button',{name:'当前应用版本',exact:true}).waitFor();c=await call('GET',`/instances/${i.id}/images`);assert.equal(c.execution.imageId,initial);assert.equal(c.pendingUpdates,0);checks.push('selecting matching bytes pins the app without unnecessary environment updates');
  const next='sha256:'+'2'.repeat(64);fs.writeFileSync(path.join(engine,'images.json'),JSON.stringify({tags:{'news:1.0':next}}));await page.getByRole('button',{name:'登记镜像',exact:true}).click();await page.getByRole('button',{name:'检查并登记',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.image-version').length===2);c=await call('GET',`/instances/${i.id}/images`);const newer=c.versions.find(x=>x.imageId===next);assert.equal(c.execution.imageId,initial);checks.push('same tag with different bytes creates a new version and retains the old one');
  await page.locator(`[data-image-version-id="${newer.id}"]`).getByRole('button',{name:'设为应用版本',exact:true}).click();await page.getByRole('button',{name:'更新此环境',exact:true}).waitFor();c=await call('GET',`/instances/${i.id}/images`);assert.equal(c.pendingUpdates,1);assert.equal(c.environments[0].imageId,initial);checks.push('target selection exposes pending impact and preserves the running environment');
  const out='docs/screenshots/0.12.0';fs.mkdirSync(out,{recursive:true});await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/images-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'← 返回应用',exact:true}).click();await page.locator('#application-image-summary').getByText(/1 个待更新/).waitFor();await page.screenshot({path:out+'/image-summary-desktop.png'});await page.getByRole('button',{name:'镜像与构建',exact:true}).click();await page.locator('.image-usage').waitFor();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/images-mobile.png',fullPage:true});await page.locator('.image-environment').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/images-mobile-environments.png'});await page.locator('.image-detail h3').last().scrollIntoViewIfNeeded();await page.screenshot({path:out+'/images-mobile-metadata.png'});assert(await page.evaluate(()=>document.querySelector('#applications-page').scrollWidth<=document.querySelector('#applications-page').clientWidth));checks.push('app summary and image page expose updates and fit mobile');
  fs.writeFileSync(path.join(engine,'images.json'),JSON.stringify({tags:{'news:1.0':next},missing:[next]}));await page.getByRole('button',{name:'更新此环境',exact:true}).click();await page.locator('.image-environment .error').filter({hasText:'无法检查'}).waitFor();let actual=JSON.parse(fs.readFileSync(path.join(engine,'state.json')))[v.containerName];assert.equal(actual.Image,initial);assert.equal(actual.State.Status,'running');checks.push('missing target image is visible and cannot destroy the old running container');
  fs.writeFileSync(path.join(engine,'images.json'),JSON.stringify({tags:{'news:1.0':'sha256:'+'3'.repeat(64)}}));await page.getByRole('button',{name:'更新此环境',exact:true}).click();await page.getByText('版本一致',{exact:true}).waitFor();actual=JSON.parse(fs.readFileSync(path.join(engine,'state.json')))[v.containerName];assert.equal(actual.Image,next);assert.equal(fs.readFileSync(path.join(v.codexHome,'keep.txt'),'utf8'),'persistent');checks.push('explicit update uses selected immutable bytes after tag drift and preserves data');
  fs.writeFileSync(path.join(engine,'offline'),'1');await page.locator(`[data-image-version-id="${newer.id}"]`).getByRole('button',{name:'检查可用性',exact:true}).click();await page.getByText('检查未通过',{exact:true}).waitFor();await page.reload();await page.getByText('检查未通过',{exact:true}).waitFor();assert.equal(await page.locator('.image-version').count(),2);fs.unlinkSync(path.join(engine,'offline'));checks.push('offline check result and image history remain available after page reload');
  await page.locator(`[data-image-version-id="${newer.id}"]`).getByRole('button',{name:'检查可用性',exact:true}).click();await page.getByText('检查未通过',{exact:true}).waitFor({state:'detached'});checks.push('a later successful check clears the previous failure');
  const calls=fs.readFileSync(path.join(engine,'calls.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert(!calls.some(x=>['build','pull','run'].includes(x[0])));assert.deepEqual(errors,[]);checks.push('no implicit build, pull, image execution or browser errors');
  const report={mode:'fake local Docker CLI; no real Docker/model',passed:checks.length,checks};fs.writeFileSync('docs/images-validation-0.12.0.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }catch(e){console.error(e.stack,logs);if(page)await page.screenshot({path:path.join(temp,'failure.png')}).catch(()=>{});console.error('fixture debug directory',temp);process.exitCode=1;}
 finally{await browser?.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}if(!process.exitCode)fs.rmSync(temp,{recursive:true,force:true});}
})();
