// Personal library browser test; native demo App Server, no real model.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-library-')),port=35000+Math.floor(Math.random()*15000),base=`http://127.0.0.1:${port}`,token='library-admin-token-123456789',checks=[],errors=[];let browser,page,logs='';const server=spawn(path.resolve('bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,RUNDESK_TOKEN:token},stdio:['ignore','ignore','pipe']});server.stderr.on('data',x=>logs+=x);
const call=async(method,p,body)=>{const r=await fetch(base+'/api/v1'+p,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)});const v=await r.json();assert(r.ok,JSON.stringify(v));return v;};
try{for(let n=0;n<100;n++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(base);await page.locator('#token').fill(token);await page.locator('#login-form button').click();await page.waitForFunction(()=>state.workspaces.length>0);
await page.locator('#attach').click();await page.getByRole('button',{name:'上传文件',exact:true}).click();await page.locator('#upload').setInputFiles({name:'research-notes.txt',mimeType:'text/plain',buffer:Buffer.from('私人新闻背景资料')});await page.locator('#attachments').filter({hasText:'research-notes.txt'}).waitFor();let files=await call('GET','/library');assert.equal(files.length,1);const uploaded=files[0];assert.equal(uploaded.kind,'upload');checks.push('plus menu uploads an attachment and automatically saves it in personal library');
await page.locator('#nav-library').click();await page.locator('.personal-library-row').filter({hasText:'research-notes.txt'}).waitFor();await page.getByRole('button',{name:'research-notes.txt',exact:true}).click();await page.locator('.personal-library-text').filter({hasText:'私人新闻背景资料'}).waitFor();await page.locator('dialog[open]').last().getByRole('button',{name:'关闭',exact:true}).click();await page.locator('.personal-library-dialog').getByRole('button',{name:'关闭',exact:true}).click();checks.push('personal library previews uploaded text');
await page.locator('#prompt').fill('请根据附件生成研究报告');await page.locator('#composer').evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>state.session?.status==='completed');await page.waitForTimeout(300);files=await call('GET','/library');assert(files.some(f=>f.kind==='generated'&&f.name==='demo-report.md'));const firstSession=await page.evaluate(()=>state.session.id);checks.push('completed conversation automatically saves generated report');
await page.evaluate(()=>newSession());await page.locator('#attach').click();await page.getByRole('button',{name:'从文件库加入',exact:true}).click();await page.getByRole('searchbox',{name:'搜索文件名'}).fill('research-notes');await page.locator('.personal-library-row').filter({hasText:'research-notes.txt'}).getByRole('button',{name:'加入',exact:true}).click();await page.locator('#attachments').filter({hasText:'research-notes.txt'}).waitFor();await page.locator('#prompt').fill('在新的会话中使用这些资料');await page.locator('#composer').evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>state.session?.status==='completed');assert.notEqual(await page.evaluate(()=>state.session.id),firstSession);checks.push('another session selects and uses the same personal file through plus');
await page.locator('#nav-library').click();await page.locator('.personal-library-row').filter({hasText:'demo-report.md'}).first().waitFor();const out='docs/screenshots/0.13.0';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/personal-library-desktop.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/personal-library-mobile.png'});assert(await page.evaluate(()=>document.querySelector('.personal-library-dialog').scrollWidth<=document.querySelector('.personal-library-dialog').clientWidth));checks.push('personal file list fits desktop and mobile');await page.setViewportSize({width:1440,height:1000});
await page.locator('.personal-library-row').filter({hasText:'research-notes.txt'}).getByRole('button',{name:'删除',exact:true}).click();await page.locator('.personal-library-row').filter({hasText:'research-notes.txt'}).waitFor({state:'detached'});assert.equal((await page.request.get(base+'/api/v1/library/'+uploaded.id+'/content')).status(),410);await page.locator('.personal-library-dialog').getByRole('button',{name:'关闭',exact:true}).click();await page.evaluate(()=>loadFiles());await page.locator('.message.user').filter({hasText:'文件已删除'}).waitFor();checks.push('deleting removes the library entry and marks historical attachment deleted');
await call('DELETE','/sessions/'+firstSession);files=await call('GET','/library');assert(files.some(f=>f.sessionId===firstSession));await page.reload();await page.locator('#nav-library').click();await page.locator('.personal-library-row').filter({hasText:'demo-report.md'}).first().waitFor();checks.push('library files survive session deletion and page reload');assert.deepEqual(errors,[]);checks.push('no uncaught browser exceptions');const report={mode:'native demo App Server; no real model',passed:checks.length,checks};fs.writeFileSync('docs/library-validation-0.13.0.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}catch(e){console.error(e.stack,logs);await page?.screenshot({path:path.join(temp,'failure.png')}).catch(()=>{});console.error(temp);process.exitCode=1;}finally{await browser?.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}if(!process.exitCode)fs.rmSync(temp,{recursive:true,force:true});}})();
