// Real HTTP/UI; Codex side is the explicit demo protocol fixture.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-product-')),port=33000+Math.floor(Math.random()*18000),base=`http://127.0.0.1:${port}`,token='product-test-token-1234567890';
 const server=spawn(path.resolve(process.env.RUNDESK_BINARY||'bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,RUNDESK_TOKEN:token},stdio:['ignore','ignore','pipe']});let logs='',browser,page;server.stderr.on('data',x=>logs+=x);const checks=[],errors=[];
 const call=async(method,p,body)=>{const r=await fetch(base+'/api/v1'+p,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)});assert(r.ok,`${method} ${p}: ${r.status} ${await r.clone().text()}`);return r.json();};
 const out=path.resolve('docs/screenshots/0.8.1');fs.mkdirSync(out,{recursive:true});
 try{
  for(let n=0;n<100;n++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
  const work=(await call('GET','/workspaces'))[0],news=await call('POST','/instances',{name:'News2Douyin',defaultModel:'demo-research'}),video=await call('POST','/instances',{name:'RunDesk Video'});
  await call('PUT','/applications/news2douyin',{name:'News2Douyin',description:'追溯新闻背景与原始证据，形成有依据的研究报告。',instanceId:news.id,workspaceId:work.id,entryUrl:'http://localhost:18080'});
  const task=await call('POST','/sessions',{instanceId:news.id,workspaceId:work.id,title:'美联储政策变化：背景与市场影响',source:{kind:'application',appId:'news2douyin',taskId:'research-fixture'}});
  await call('POST','/sessions',{instanceId:video.id,workspaceId:work.id,title:'新闻解读视频：分镜与素材',source:{kind:'application',appId:'rundesk-video-app',taskId:'video-fixture'}});const orphan=await call('POST','/instances',{name:'历史研究配置'});
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
  const long='Follow this skill when investigating a news event. Trace original sources, compare evidence and verify dates. '.repeat(8);
  // Layout fixture: demo uses generic descriptions, so provide a deliberately long one.
  await page.route('**/api/v1/workspaces/*/skills?*',async route=>{const response=await route.fetch();const raw=await response.json();for(const d of raw.data||[])for(const sk of d.skills||[])if(sk.name==='research')sk.description=long;await route.fulfill({response,json:raw});});
  await page.goto(base);await page.locator('#token').fill(token);await page.locator('#login-form button').click();await page.waitForFunction(()=>state.draftContext&&state.workspaces.length);
  assert.equal(await page.locator('#page-label').innerText(),'通用助手');assert.equal(await page.locator('#instance').isVisible(),false);assert.equal(await page.locator('#session-list .session').count(),0);await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/assistant-desktop.png'});checks.push('default general assistant has no instance picker and excludes application tasks');
  await page.locator('#prompt').fill('保留助手草稿');await page.locator('#nav-applications').click();await page.locator('.application-card').first().waitFor();assert.equal(await page.locator('.application-card').count(),2);await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/applications-desktop.png'});
  await page.locator('[data-app-id=news2douyin]').getByRole('button',{name:'查看任务'}).click();await page.locator('.application-task').waitFor();assert.equal(await page.locator('.application-task').count(),1);await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/application-desktop.png'});
  await page.getByRole('button',{name:'模型与认证 模型、登录与运行权限'}).click();await page.locator('#assistant-model').fill('app-new-model');await page.getByRole('button',{name:'保存配置',exact:true}).click();await page.waitForFunction(()=>instance().defaultModel==='app-new-model');assert.equal((await call('GET','/instances')).find(x=>x.id==='default').defaultModel,'');assert.equal((await call('GET','/sessions/'+task.id)).model,'demo-research');await page.locator('#close-settings').click();checks.push('application model changes preserve assistant defaults and existing task models');
  await page.getByRole('button',{name:'技能 Skills 完整目录与工作方法'}).click();await page.locator('#skill-directory-input').waitFor({state:'attached'});assert.equal(await page.locator('#settings').isVisible(),false);assert.equal(await page.locator('#capability-page h1').innerText(),'技能 Skills');
  const folder=path.join(temp,'research');fs.mkdirSync(path.join(folder,'scripts'),{recursive:true});fs.mkdirSync(path.join(folder,'references'),{recursive:true});fs.mkdirSync(path.join(folder,'assets'),{recursive:true});fs.writeFileSync(path.join(folder,'SKILL.md'),'---\nname: research\ndescription: Research with evidence\n---\nRead references and run scripts.');fs.writeFileSync(path.join(folder,'scripts/research.py'),'#!/usr/bin/env python3\nprint("fixture only")\n');fs.writeFileSync(path.join(folder,'references/background.md'),'Original context and primary evidence.');fs.writeFileSync(path.join(folder,'assets/template.bin'),Buffer.from([0,1,2,255]));
  await page.locator('#skill-directory-input').setInputFiles(folder);await page.locator('#skill-bundle-name').waitFor();assert.equal(await page.locator('#skill-bundle-name').inputValue(),'research');await page.locator('#skill-bundle-submit').click();const row=page.locator('.skill-row').filter({has:page.locator('strong',{hasText:'research'})});await row.waitFor();await page.locator('.skill-import-dialog').waitFor({state:'detached'});
  const bp=`/workspaces/${work.id}/skill-bundles/research?instanceId=${news.id}&scope=instance`;let manifest=await call('GET',bp);assert.equal(manifest.files.length,4);assert(manifest.files.find(x=>x.path==='scripts/research.py').executable);const general=await call('GET',`/instances/default/configuration?workspaceId=${work.id}&probe=1`);assert(!general.skills.some(x=>x.name==='research'));checks.push('folder import preserves script, reference and binary assets in application scope');
  assert.equal(await row.locator('.skill-enable').innerText(),'启用');assert((await row.locator('.skill-use').boundingBox()).width>140);assert((await row.locator('.skill-use').boundingBox()).height<50);assert.equal(await page.locator('.configuration-editor').evaluate(n=>n.open),false);await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/skills-desktop.png'});
  await row.getByRole('button',{name:'目录',exact:true}).click();await page.locator('.skill-file').filter({hasText:'references/background.md'}).click();await page.locator('.skill-file-preview pre').waitFor();assert((await page.locator('.skill-file-preview pre').innerText()).includes('Original context'));await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/skill-directory-desktop.png'});await page.locator('.skill-file').filter({hasText:'assets/template.bin'}).click();await page.getByText('二进制文件，完整内容包含在导出的 ZIP 中。').waitFor();await page.locator('.skill-directory-dialog').getByRole('button',{name:'关闭',exact:true}).click();
  const downloadPromise=page.waitForEvent('download');await row.getByRole('button',{name:'导出 ZIP',exact:true}).click();const download=await downloadPromise,zip=path.join(temp,'research.zip');await download.saveAs(zip);assert(fs.statSync(zip).size>0);
  await row.getByRole('button',{name:'编辑',exact:true}).click();await page.locator('#skill-content').fill('---\nname: research\ndescription: Edited documentation\n---\nChanged only SKILL.md.');await page.getByRole('button',{name:'保存并重新扫描'}).click();await row.waitFor();manifest=await call('GET',bp);assert.equal(manifest.files.length,4);assert((await call('GET',bp.replace('research?','research/file?')+'&path=scripts%2Fresearch.py')).text.includes('fixture only'));checks.push('directory browser previews text/binary; ZIP export and MD edits retain sibling files');
  await page.locator('#skill-zip-input').setInputFiles(zip);await page.locator('#skill-bundle-submit').click();await page.locator('.skill-import-dialog .error').filter({hasText:'同名技能已存在'}).waitFor();await page.locator('#skill-bundle-replace').check();await page.locator('#skill-bundle-submit').click();await page.locator('.skill-import-dialog').waitFor({state:'detached'});await row.waitFor();assert.equal((await call('GET',bp)).files.length,4);checks.push('ZIP import rejects silent overwrite and supports explicit backed-up replacement');
  await page.reload();await page.locator('#capability-page h1').waitFor();await row.waitFor();assert.equal(await page.locator('#page-label').innerText(),'News2Douyin');checks.push('independent Skills page refresh retains application ownership');
  await page.getByRole('button',{name:'管理 MCP 工具',exact:true}).click();await page.locator('#mcp-name').waitFor({state:'attached'});assert.equal(await page.locator('#capability-page h1').innerText(),'工具 MCP');await page.locator('#capability-content .configuration-editor>summary').click();await page.locator('#mcp-name').fill('evidence-source');await page.locator('#mcp-type').selectOption('http');await page.locator('#mcp-url').fill('http://127.0.0.1:18999/mcp');await page.locator('#mcp-enabled').uncheck();await page.getByRole('button',{name:'保存配置',exact:true}).click();await page.locator('.skill-row').filter({hasText:'evidence-source'}).waitFor();assert.equal(await page.locator('.configuration-editor').evaluate(n=>n.open),false);await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/mcp-desktop.png'});const g=await call('GET',`/workspaces/${work.id}/mcp?instanceId=default`);assert(!g.userServers['evidence-source']);checks.push('independent MCP page keeps forms collapsed and writes only the chosen application');
  await page.getByRole('button',{name:'← 返回',exact:true}).click();await page.locator('.application-task').click();await page.waitForFunction(()=>state.session?.source?.appId==='news2douyin');await page.locator('#trace-button').click();await page.locator('#trace-workspace').waitFor();await page.reload();await page.locator('#trace-workspace').waitFor();assert.equal(await page.evaluate(()=>state.session.source.appId),'news2douyin');await page.locator('#trace-close').click();checks.push('application trace refresh returns to the same task');
  await page.locator('#prompt').fill('应用任务草稿');await page.locator('#nav-assistant').click();await page.waitForFunction(()=>instance().id==='default');await page.locator('#prompt').fill('通用助手草稿');await page.locator('#nav-applications').click();await page.locator('[data-app-id=news2douyin]').getByRole('button',{name:'查看任务'}).click();await page.locator('.application-task').click();await page.waitForFunction(()=>state.session?.source?.appId==='news2douyin');assert.equal(await page.locator('#prompt').inputValue(),'应用任务草稿');await page.locator('#nav-assistant').click();await page.waitForFunction(()=>instance().id==='default');assert.equal(await page.locator('#prompt').inputValue(),'通用助手草稿');checks.push('assistant and application drafts remain separate');
  await page.locator('#prompt').fill('通用助手发送验证');await page.locator('#send').click();await page.waitForFunction(()=>state.session?.status==='completed');await page.locator('#new-session').click();await page.waitForFunction(()=>!state.session);assert.equal(await page.locator('#prompt').inputValue(),'');checks.push('new conversation sends successfully and accepted messages do not return as drafts');
  await page.locator('#assistant-settings').click();await page.locator('[data-settings-tab=instances]').click();await page.locator('#assistant-model').fill('general-model');await page.getByRole('button',{name:'保存配置',exact:true}).click();await page.waitForFunction(()=>instance().defaultModel==='general-model');assert.equal((await call('GET','/instances')).find(i=>i.id===news.id).defaultModel,'app-new-model');await page.locator('#close-settings').click();
  await page.locator('#nav-applications').click();await page.locator('.application-card').first().waitFor();await page.getByRole('button',{name:'添加应用',exact:true}).click();await page.locator('#register-app-id').fill('custom-app');await page.locator('#register-app-name').fill('资料整理');await page.locator('.application-register button[type=submit]').click();await page.locator('.application-empty.compact').waitFor();assert.equal((await call('GET','/applications/custom-app')).sessionCount,0);await page.locator('#back-applications').click();await page.locator('#application-advanced>summary').click();await page.locator('.legacy-application').filter({hasText:'历史研究配置'}).getByRole('button',{name:'登记为应用'}).click();await page.locator('#register-app-id').fill('legacy-research');await page.locator('.application-register button[type=submit]').click();await page.waitForFunction(()=>state.applications.some(a=>a.appId==='legacy-research'));assert.equal((await call('GET','/applications/legacy-research')).instanceId,orphan.id);checks.push('new zero-task apps and legacy configuration registration work without replacing identities');
  await page.setViewportSize({width:390,height:844});await page.locator('#back-applications').click();await page.locator('.application-card').first().waitFor();await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/applications-mobile.png'});await page.locator('[data-app-id=news2douyin]').getByRole('button',{name:'查看任务'}).click();await page.getByRole('button',{name:'技能 Skills 完整目录与工作方法'}).click();await row.waitFor();await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/skills-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert((await row.locator('.skill-use').boundingBox()).height<50);await row.getByRole('button',{name:'目录',exact:true}).click();await page.locator('.skill-file').filter({hasText:'scripts/research.py'}).click();await page.locator('.skill-file-preview pre').waitFor();await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/skill-directory-mobile.png'});assert(await page.evaluate(()=>document.querySelector('.skill-directory-dialog').scrollWidth<=document.querySelector('.skill-directory-dialog').clientWidth));await page.locator('.skill-directory-dialog').getByRole('button',{name:'关闭',exact:true}).click();await page.locator('#sidebar-toggle').click();await page.locator('#nav-assistant').click();await page.waitForFunction(()=>instance().id==='default');await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/assistant-mobile.png'});checks.push('390px mobile pages, directory viewer and skill controls fit without horizontal overflow');
  assert.deepEqual(errors,[]);checks.push('no page JavaScript errors');const report={mode:'RunDesk 0.8.1 demo protocol; no live model or external MCP execution',passed:checks.length,checks};fs.writeFileSync('docs/product-validation-0.8.1.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }catch(e){if(page){await page.locator('#toast').evaluate(n=>n.classList.add('hidden'));await page.screenshot({path:out+'/failure.png'});console.error(await page.locator('body').innerText());}console.error(logs);throw e;}finally{await browser?.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}fs.rmSync(temp,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
