const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-queue-')),port=35000+Math.floor(Math.random()*15000),base=`http://127.0.0.1:${port}`,token='queue-demo-admin-token-1234567890',checks=[];let browser,page;const errors=[];
const server=spawn(path.resolve('bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,RUNDESK_TOKEN:token},stdio:'ignore'});
try{for(let n=0;n<100;n++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox']});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('#token').fill(token);await page.locator('#login-form button').click();await page.waitForFunction(()=>state.workspaces.length>0);await page.locator('#nav-tasks').click();await page.locator('#queue-toggle').click();await page.locator('#queue-toggle').filter({hasText:'恢复调度'}).waitFor();
await page.locator('#new-task').click();await page.locator('#task-title').fill('每日新闻研究');await page.locator('#task-text').fill('审批：研究新闻背景');await page.locator('.task-dialog button[type=submit]').click();await page.locator('.queue-task').waitFor();assert.match(await page.locator('.queue-task').innerText(),/排队中/);checks.push('paused queue persists a new task from the UI');
await page.locator('.queue-task summary').click();await page.locator('.queue-task').getByRole('button',{name:'查看会话与过程'}).click();await page.locator('#queue-banner').filter({hasText:'排队中'}).waitFor();assert(await page.locator('#send').isDisabled());checks.push('reserved session shows queue ownership and disables direct submission');
await page.locator('#nav-tasks').click();await page.locator('#queue-toggle').click();await page.locator('.queue-task').filter({hasText:'等待确认'}).waitFor();if(!await page.locator('.queue-task').evaluate(d=>d.open))await page.locator('.queue-task summary').click();await page.locator('.queue-task').getByRole('button',{name:'取消任务'}).click();await page.locator('.queue-task').filter({hasText:'已停止'}).waitFor();checks.push('native demo approval consumes capacity and task cancellation reaches interrupted');
await page.locator('#queue-settings').click();await page.locator('#queue-max').fill('2');await page.locator('.task-dialog button[type=submit]').click();await page.locator('#queue-summary').filter({hasText:'全局最多 2'}).waitFor();checks.push('concurrency revision is saved');
const out='docs/screenshots/0.9.2';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/tasks-desktop.png'});await page.reload();await page.locator('.queue-task').waitFor();assert.equal(await page.locator('.queue-task').count(),1);checks.push('route and stored task survive page reload');await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/tasks-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('mobile page fits 390px width');assert.deepEqual(errors,[]);checks.push('no uncaught browser error');const report={mode:'native demo JSONL, no live model',passed:checks.length,checks};fs.writeFileSync('docs/queue-validation-0.9.2.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}catch(e){console.error(e);if(page)console.error(await page.locator('body').innerText());process.exitCode=1;}finally{await browser?.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}fs.rmSync(temp,{recursive:true,force:true});}})();
