// Real Go service and Chromium; native Codex is an explicitly selected demo fixture.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-recovery-')),port=35000+Math.floor(Math.random()*15000),base=`http://127.0.0.1:${port}`,token='recovery-test-token-1234567890';
 const server=spawn(path.resolve('bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,RUNDESK_TOKEN:token},stdio:['ignore','ignore','pipe']});let logs='',browser,page;server.stderr.on('data',x=>logs+=x);
 const checks=[],errors=[],out=path.resolve('docs/screenshots/0.9.2');fs.mkdirSync(out,{recursive:true});
 const send=async text=>{await page.locator('#prompt').fill(text);await page.locator('#send').click();};
 try{
  for(let n=0;n<100;n++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await page.locator('#token').fill(token);await page.locator('#login-form button').click();await page.waitForFunction(()=>state.workspaces.length>0);
  await send('恢复演示：整理新闻背景，生成报告');await page.waitForFunction(()=>state.session?.status==='failed');const source=await page.evaluate(()=>({...state.session}));
  await page.locator('#prompt').fill('保留这条未发送的草稿');await page.locator('#recovery-banner').getByRole('button',{name:'核对并继续'}).click();await page.locator('#recovery-reviewed').waitFor();
  assert.match(await page.locator('#recovery-content').innerText(),/恢复演示：整理新闻背景/);assert.match(await page.locator('#recovery-content').innerText(),/recovery-draft.md/);assert.match(await page.locator('#recovery-content').innerText(),/命令/);assert(await page.locator('#recovery-submit').isDisabled());
  await page.locator('.recovery-file').click();await page.locator('#preview-content pre').waitFor();assert.match(await page.locator('#preview-content').innerText(),/恢复演示草稿/);await page.locator('#close-preview').click();assert(await page.locator('#recovery-dialog').isVisible());
  await page.screenshot({path:out+'/recovery-desktop.png'});checks.push('failed demo task shows original goal, native failure, completed step and existing file with safe preview; acknowledgement required');
  await page.keyboard.press('Escape');assert(!await page.locator('#recovery-dialog').isVisible());assert.equal(await page.locator('#prompt').inputValue(),'保留这条未发送的草稿');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'核对并继续');
  await page.locator('#recovery-banner button').click();await page.locator('#recovery-reviewed').check();await page.locator('#recovery-note').fill('草稿已保存，尚未生成最终报告。');checks.push('Escape returns focus to the trigger and preserves the main draft');
  const requests=[];let lose=true;
  await page.route(`**/api/v1/sessions/${source.id}/recover`,async route=>{requests.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});if(lose){lose=false;const r=await route.fetch();assert.equal(r.status(),202);await route.abort('failed');}else await route.continue();});
  await page.locator('#recovery-submit').click();await page.locator('#recovery-submit').filter({hasText:'重试同一请求'}).waitFor();await page.waitForFunction(()=>!document.querySelector('#recovery-submit').disabled);await page.locator('#recovery-submit').click();await page.locator('#recovery-dialog').waitFor({state:'hidden'});
  await page.waitForFunction(()=>state.session?.status==='completed');const done=await page.evaluate(()=>({...state.session}));assert.equal(done.id,source.id);assert.equal(done.threadId,source.threadId);assert.notEqual(done.runId,source.runId);assert.equal(done.recovery.sourceRunId,source.runId);assert.equal(requests.length,2);assert.deepEqual(requests[0],requests[1]);assert.equal(await page.locator('#prompt').inputValue(),'保留这条未发送的草稿');
  checks.push('lost acceptance response is retried with the identical key and body; original session/thread, new run, origin link and draft retained');
  await page.locator('#trace-button').click();await page.locator('.trace-turn').nth(1).waitFor();assert.equal(await page.locator('.trace-turn').count(),2);assert.match(await page.locator('.trace-turn').first().innerText(),/失败/);assert.match(await page.locator('.trace-turn').nth(1).innerText(),/恢复轮次/);
  await page.locator('.trace-round').nth(1).click();await page.locator('#trace-context').getByRole('button',{name:'查看来源轮次'}).click();assert.equal(await page.locator('.trace-turn.expanded').getAttribute('data-run'),source.runId);await page.screenshot({path:out+'/recovery-trace.png'});await page.locator('#trace-close').click();checks.push('single timeline preserves the failed source and completed continuation with source navigation');
  await page.locator('#new-session').click();await send('重试演示');await page.waitForFunction(()=>state.session?.retry);assert.match(await page.locator('#recovery-banner').innerText(),/Codex 正在重试/);assert.equal(await page.locator('#recovery-banner button').count(),0);await page.waitForFunction(()=>state.session?.status==='completed');assert.equal(await page.evaluate(()=>state.session.retry||null),null);checks.push('native willRetry remains the same active task, offers no duplicate start and clears after progress');
  await page.locator('#new-session').click();await send('恢复演示：移动端核对');await page.waitForFunction(()=>state.session?.status==='failed');await page.setViewportSize({width:390,height:844});await page.locator('#recovery-banner button').click();await page.locator('#recovery-reviewed').waitFor();await page.screenshot({path:out+'/recovery-mobile.png'});assert(await page.locator('#recovery-dialog').evaluate(n=>n.scrollWidth<=n.clientWidth+1));await page.locator('#recovery-reviewed').scrollIntoViewIfNeeded();await page.screenshot({path:out+'/recovery-mobile-review.png'});await page.keyboard.press('Escape');assert(await page.locator('#shell').evaluate(n=>n.scrollWidth<=n.clientWidth+1));checks.push('390px recovery dialog, evidence and review controls fit without horizontal overflow');
  const blockedSid=await page.evaluate(()=>state.session.id);let recoverCalls=0;
  await page.route(`**/api/v1/sessions/${blockedSid}/recovery/check`,async route=>{const response=await route.fetch(),p=await response.json();p.canContinue=false;p.category='completed';p.native.turnStatus='completed';p.native.reply='原生结果已经生成。';p.reason='原生轮次已经完成；请查看返回内容和产物，本次不重复执行。';await route.fulfill({response,json:p});});
  await page.route(`**/api/v1/sessions/${blockedSid}/recover`,async route=>{recoverCalls++;await route.continue();});
  await page.locator('#recovery-banner button').click();await page.locator('.recovery-result.blocked').waitFor();assert(await page.locator('#recovery-submit').isDisabled());assert.match(await page.locator('#recovery-content').innerText(),/原生结果已经生成/);assert.equal(await page.locator('#recovery-reviewed').count(),0);assert.equal(recoverCalls,0);checks.push('blocked completed-state preview displays native reply and cannot submit a continuation (UI fixture; server gate covered in Go)');
  assert.deepEqual(errors,[]);checks.push('no uncaught browser JavaScript errors');
  const report={mode:'RunDesk demo JSONL fixture, persisted demo thread state, Chromium response-loss injection; no live model or external business write',passed:checks.length,checks};fs.writeFileSync('docs/recovery-validation-0.9.2.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }catch(e){if(page){await page.screenshot({path:out+'/recovery-failure.png'}).catch(()=>{});console.error(await page.locator('body').innerText());}console.error(e);console.error(logs.slice(-1500));process.exitCode=1;}
 finally{await browser?.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}fs.rmSync(temp,{recursive:true,force:true});}
})();
