const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rd-register-')),port=36000+Math.floor(Math.random()*1500),base='http://127.0.0.1:'+port;const proc=spawn('./bin/rundesk',['--demo','--data',temp,'--listen','127.0.0.1:'+port],{env:{...process.env,RUNDESK_TOKEN:'',CODEX_BASE_TOKEN:''}});let browser;const errors=[],checks=[];try{
for(let n=0;n<100;n++){try{if((await fetch(base+'/api/v1/meta')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
let r=await fetch(base+'/api/v1/applications/news2douyin/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'新闻研究',description:'研究新闻并保存报告',installationId:'browser-test',defaults:{}})});assert.equal(r.status,200);const binding=await r.json();assert.equal(binding.status,'connected');
browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1320,height:900}});page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/#applications');await page.getByRole('heading',{name:'新闻研究',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'添加应用',exact:true}).count(),0);checks.push('application appears automatically without manual creation');
await page.getByRole('button',{name:'查看任务',exact:true}).click();await page.getByRole('button',{name:'选用已有能力'}).click();await page.getByRole('heading',{name:'选用已有能力'}).waitFor();await page.getByRole('button',{name:'取消',exact:true}).click();checks.push('administrator can open capability selection');
const out='docs/screenshots/0.15.0';fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/application.png'});
await page.goto(base+'/collaboration.html');await page.locator('#create').click();await page.getByLabel('希望完成什么？').fill('调查新闻背景，并汇总结果');assert.equal(await page.getByLabel('负责人',{exact:true}).inputValue(),'rundesk-assistant');assert.equal(await page.getByLabel('交互方式').inputValue(),'p2p');assert.equal(await page.locator('#fields details').getAttribute('open'),null);checks.push('collaboration defaults to assistant and workers; advanced options collapsed');await page.screenshot({path:out+'/collaboration.png'});
await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('mobile fits viewport');assert.deepEqual(errors,[]);checks.push('no browser exceptions');fs.writeFileSync('docs/registration-ui-validation.json',JSON.stringify({checks,passed:checks.length},null,2));console.log(JSON.stringify(checks));
}finally{await browser?.close();proc.kill();await new Promise(r=>proc.once('exit',r));fs.rmSync(temp,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
