// Browser/API member isolation against fake Docker + native demo protocol; no real model.
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const {spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rundesk-users-')),cli=path.join(temp,'cli'),engine=path.join(temp,'engine');fs.mkdirSync(cli);fs.mkdirSync(engine);const fixture=path.join(cli,'docker');fs.copyFileSync('scripts/fixtures/docker-engine.py',fixture);fs.chmodSync(fixture,0o755);
 const port=35000+Math.floor(Math.random()*15000),base=`http://127.0.0.1:${port}`,token='users-demo-admin-token-1234567890',checks=[],errors=[];let browser,admin,member,viewer,logs='';
 const server=spawn(path.resolve('bin/rundesk'),['--demo','--data',temp,'--listen',`127.0.0.1:${port}`],{env:{...process.env,PATH:cli+path.delimiter+process.env.PATH,DOCKER_CONFIG:engine,RUNDESK_TOKEN:token},stdio:['ignore','ignore','pipe']});server.stderr.on('data',x=>logs+=x);
 const call=async(method,p,body,bearer=token)=>{const r=await fetch(base+'/api/v1'+p,{method,headers:{Authorization:'Bearer '+bearer,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();assert(r.ok,`${method} ${p}: ${r.status} ${JSON.stringify(data)}`);return data;};
 async function login(page,secret){page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.locator('#token').fill(secret);await page.locator('#login-form button').click();}
 try{
  for(let n=0;n<100;n++){try{if((await fetch(base+'/api/meta')).status===401)break;}catch{}await new Promise(r=>setTimeout(r,80));}
  let i=await call('POST','/instances',{name:'新闻研究'});i=await call('PUT',`/instances/${i.id}/execution`,{revision:i.revision,spec:{mode:'docker',image:'news:1.0'}});const w=await call('POST','/workspaces',{name:'编辑共享项目'}),privateW=await call('POST','/workspaces',{name:'独立保密项目'});await call('PUT','/applications/news',{name:'新闻研究',instanceId:i.id,workspaceId:w.id});for(const ws of [w,privateW])await call('POST','/environments',{instanceId:i.id,workspaceId:ws.id});const privateS=await call('POST','/sessions',{instanceId:i.id,workspaceId:privateW.id,title:'不可见的研究',source:{kind:'application',appId:'news'}});
  browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});admin=await browser.newPage({viewport:{width:1440,height:1000}});await login(admin,token);await admin.locator('#nav-users').click();await admin.getByRole('button',{name:'创建用户',exact:true}).click();await admin.locator('#user-name').fill('新闻编辑');const row=admin.locator('.user-project-option').filter({hasText:'编辑共享项目'});await row.locator('input').check();await row.locator('select').selectOption('runner');await admin.getByRole('button',{name:'创建并生成访问码',exact:true}).click();await admin.locator('#user-access-code').waitFor();const code=await admin.locator('#user-access-code').inputValue();assert(code.startsWith('rd_user_'));await admin.locator('.user-code-dialog').getByRole('button',{name:'关闭',exact:true}).click();await admin.locator('#user-access-code').waitFor({state:'detached'});checks.push('admin creates a project-scoped user and displays the access code once');
  const u=(await call('GET','/users'))[0];assert.equal(u.grants.length,1);assert.equal(u.grants[0].role,'runner');const read=await call('POST','/users',{name:'新闻审阅',grants:[{appId:'news',workspaceId:w.id,role:'viewer'}]});
  const out='docs/screenshots/0.11.0';fs.mkdirSync(out,{recursive:true});await admin.getByRole('button',{name:'刷新',exact:true}).click();await admin.locator('.user-card').filter({hasText:'新闻审阅'}).waitFor();await admin.screenshot({path:out+'/users-desktop.png'});await admin.setViewportSize({width:390,height:844});await admin.screenshot({path:out+'/users-mobile.png'});assert(await admin.evaluate(()=>document.querySelector('#applications-page').scrollWidth<=document.querySelector('#applications-page').clientWidth));checks.push('user management fits desktop and 390px mobile');await admin.setViewportSize({width:1440,height:1000});
  member=await browser.newPage({viewport:{width:1440,height:1000}});await login(member,code);await member.waitForURL('**/member.html*');await member.locator('.project').waitFor();assert.equal(await member.locator('.project').count(),1);assert(!(await member.locator('body').innerText()).includes('独立保密项目'));await member.screenshot({path:out+'/member-projects.png'});checks.push('personal login opens member UI with only assigned application projects');
  await member.getByRole('button',{name:'进入项目',exact:true}).click();await member.locator('#member-prompt').fill('请研究这条新闻的背景');await member.locator('#member-send').click();await member.locator('#member-status').filter({hasText:'已完成'}).waitFor();await member.locator('.message.assistant').first().waitFor();assert((await member.locator('#member-events details').count())>0);const sid=(await call('GET','/member/'+u.grants[0].id+'/sessions',undefined,code))[0].id;const dir=path.join(w.path,'outputs',sid);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'report.txt'),'member project report');await member.locator('#member-files a').filter({hasText:'report.txt'}).waitFor();const href=await member.locator('#member-files a').filter({hasText:'report.txt'}).getAttribute('href');const file=await member.request.get(base+href);assert.equal(await file.text(),'member project report');checks.push('runner executes through Docker demo, sees the process and downloads project output');
  const scoped='/api/v1/member/'+u.grants[0].id;for(const p of [scoped+'/sessions/'+privateS.id,scoped+'/sessions/'+privateS.id+'/export','/api/v1/users','/api/v1/docker/status','/api/v1/instances']){const r=await member.request.get(base+p);assert.equal(r.status(),403,p);}checks.push('browser cookie cannot read another project or administrator APIs');
  await member.reload();await member.locator('.message.assistant').first().waitFor();assert((await member.url()).includes(sid));checks.push('member project and selected task survive refresh with server authorization');
  await member.locator('#member-prompt').fill('审批');await member.locator('#member-send').click();await member.getByRole('button',{name:'允许本次',exact:true}).waitFor();member.on('dialog',d=>d.accept());await member.getByRole('button',{name:'允许本次',exact:true}).click();await member.locator('#member-status').filter({hasText:'已完成'}).waitFor();checks.push('runner reviews and approves a native command request');
  await member.screenshot({path:out+'/member-task-desktop.png'});await member.setViewportSize({width:390,height:844});await member.screenshot({path:out+'/member-task-mobile.png'});assert(await member.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('member conversation fits mobile');
  viewer=await browser.newPage({viewport:{width:1200,height:900}});await login(viewer,read.accessCode);await viewer.getByRole('button',{name:'进入项目',exact:true}).click();await viewer.locator('#member-sessions button').first().click();await viewer.locator('.message.assistant').first().waitFor();assert(await viewer.locator('#member-new').isDisabled());assert.equal(await viewer.locator('#member-composer').isVisible(),false);let r=await viewer.request.post(base+scoped+'/sessions/'+sid+'/turns',{data:{text:'forbidden'}});assert.equal(r.status(),403);r=await viewer.request.post(base+scoped+'/workspaces/'+w.id+'/uploads',{data:'forbidden'});assert.equal(r.status(),403);checks.push('viewer can read shared task but server rejects turns and uploads');
  admin.on('dialog',d=>d.accept());await admin.locator(`[data-user-id="${u.id}"]`).getByRole('button',{name:'停用',exact:true}).click();await admin.locator(`[data-user-id="${u.id}"] .badge`).filter({hasText:'已停用'}).waitFor();await member.waitForURL(base+'/');await member.locator('#token').waitFor();r=await fetch(base+'/api/v1/whoami',{headers:{Authorization:'Bearer '+code}});assert.equal(r.status,401);checks.push('admin disabling user invalidates active browser login and bearer access');
  await admin.locator(`[data-user-id="${u.id}"]`).getByRole('button',{name:'启用',exact:true}).click();await admin.locator(`[data-user-id="${u.id}"] .badge`).filter({hasText:'已启用'}).waitFor();await admin.locator(`[data-user-id="${u.id}"]`).getByRole('button',{name:'重置访问码',exact:true}).click();await admin.locator('#user-access-code').waitFor();const next=await admin.locator('#user-access-code').inputValue();assert.notEqual(next,code);r=await fetch(base+'/api/v1/whoami',{headers:{Authorization:'Bearer '+code}});assert.equal(r.status,401);await call('GET','/whoami',undefined,next);await admin.locator('.user-code-dialog').getByRole('button',{name:'关闭',exact:true}).click();checks.push('access-code reset retires old code and returns a working replacement');
  assert.deepEqual(errors,[]);checks.push('no uncaught browser exceptions');const report={mode:'fake Docker CLI, native demo App Server, disposable user credentials; no real model',passed:checks.length,checks};fs.writeFileSync('docs/users-validation-0.11.0.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }catch(e){console.error(e.stack,logs);for(const [name,p]of [['admin',admin],['member',member],['viewer',viewer]])if(p)await p.screenshot({path:path.join(temp,name+'-failure.png')}).catch(()=>{});console.error('fixture debug directory',temp);process.exitCode=1;}
 finally{await browser?.close();if(server.exitCode===null){server.kill();await new Promise(r=>server.once('exit',r));}if(!process.exitCode)fs.rmSync(temp,{recursive:true,force:true});}
})();
